narmi/design_system

.github/workflows/codeql-analysis.yml

Closes https://github.com/narmi/design_system/issues/483
Enables the GitHub CodeQL Analysis bot. See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql for more information

ci: Use GitHub CodeQL Analysis

---

.storybook/main.js
.storybook/preview.js
src/ReleaseNotes.stories.mdx

fixes #480 
pulls release notes generated by semantic-release directly into storybook

docs: add release notes to storybook

---

src/base-styles/typography.scss

fixes #489 
Uses correct vars from design tokens; fixes bug with heading color

fix(typography): use correct vars from design tokens; fix heading color

---

src/Tabs/index.stories.js

Because the `Overview` story in Tabs didn't have an args passed, storybook set the second story as the primary story. This PR fixes that by adding args to `Overview`.

docs(Tabs): make Overview story the first story

---

src/LoadingShim/index.scss

Prevents loading shim from appearing under content in `banking`

fix(LoadingShim): add z-index to absolutely positioend shim

---

src/Tabs/TabsList.js
src/Tabs/TabsPanel.js

fixes #492 
For some reason, this didn't cause any issues in storybook, but in an example consumer, it threw errors.
This PR wraps the context functions that update state in the `Tabs` root component. Dependencies are injected into the `useState` so that the code is only executed when one of those dependencies changes. This prevents unnecessary state updates that were causing the error.

fix(Tabs): prevent state race condition with useEffect wrappers

---

package-lock.json
package.json

- removes unused `react-test-renderer` dependency which declares a peer dep that messes up our dependency tree
- replaces `node-sass` with `sass`. `node-sass` uses `libsass` under the hood which does not yet have support for `arm64` architecture

build(dependencies): rm react-test-renderer; replace node-sass with sass

---

src/Button/index.scss

Instead of setting a content max width on every button variant, we can set it only on the plain and secondary variants. Buttons of `plain` type should not have a restricted width.

fix(Button): remove width restriction from plain button

---

package-lock.json
package.json

This should have been a `devDependency` but I mistakenly made it a `dependency`. This PR corrects the mistake.

build(dependencies): make 'sass' a devDependency

---

.github/workflows/build.yaml
.github/workflows/github-pages.yaml
.github/workflows/jest.yaml
.github/workflows/publish_storybook.yaml

- makes all actions explicitly use node version ^16
- fixes commands for "build check" job (install with `npm ci`, run the actual build command)
A lot of this is redundant right now; in a future ticket we may be able to pass `dist` and `node_modules` from the initial build check to other actions as artifacts. (#473)

build(node version): explicitly use node version ^16 in ci

---

src/base-styles/typography.scss

This style class has relatively little usage currently so the change should be pretty safe.

fix: sub-header style should display text color as --nds-black

---

src/Row/index.js
src/Row/index.stories.js
src/Row/index.test.js

fixes #506 
Feature, story, and tests for a `justifyContent` prop on `Row`. This will make it easier to lay out content in `Dialog` footers.

feat(Row): add `justifyContent` prop

---

package-lock.json
package.json
scripts/component-adoption.mjs
scripts/util/getComponentNames.mjs
scripts/util/toAst.mjs

Adds a script that counts all NDS component imports in a given local directory.
The script converts files to AST using `@babel/parser` to ensure the es6 style destructured imports are counted correctly.
To help make sense of the AST traversal, see [this ASTExplorer example](https://astexplorer.net/#/gist/fa4070479b60f4302e0618bb8c6c26c1/ccef1f865b2064b696de3b3dbeadb670a009e55e)

build(stats): add script to check component usage in a consumer

---

src/LoadingSkeleton/index.js
src/LoadingSkeleton/index.scss
src/LoadingSkeleton/index.stories.js
src/index.js
src/index.scss

close https://github.com/narmi/design_system/issues/512
Should fit the bill as per the design spec, but not sure I love shoving both the title mask and the paragraph mask into one component. My issue is that are prop combinations that have no effect: for example, `lines` and `title` only apply if `content` is set to `paragraph`, and `size` only applies if `content` is set to `displayText`, so maybe it makes sense to have two LoadingShadow components? 
Or I suppose, we could remove the `content` prop altogether, and allow the consumer to set the number of lines, the size of the lines, and whether there is a title row regardless of how certain combinations aren't strictly compatible with the Narmi style guide. 
Then again maybe I'm overthinking it, and this is fine, as long as the props are …

feat(LoadingSkeleton): add component

---

src/Dialog/index.scss

fixes #518 
- Sets `Dialog` header text color to heading font color
- Updates border color style rule to use updated variable for primary theme color

style(Dialog): fix header text color

---

src/Button/index.scss
src/Card/index.scss
src/Dialog/index.scss
src/Input/index.scss
src/Row/index.scss
src/Row/index.stories.js
src/base-styles/defaults.scss
src/base-styles/reset.scss
src/base-styles/typography.scss
src/index.scss

fixes #494 
- Adds `reset.css` with common styles to reset/normalize elements across browsers
- Adds `defaults.css` to set NDS default styles on some base elements
- Makes some minor style fixes to bugs exposed by adding base styling
Setting foundational styles helps make NDS styling more portable and predictable across different browsers and consumers. The styles in `default.css` are also essential to overriding [underqualified selectors from semantic ui in banking](https://gist.github.com/akdetrick/72ee0385f10a5b4e14a1326e2a416acc)
---
Tested changes with `1.27.0-beta.0` in banking.
**This is not a high risk change**
`semantic-ui` still comes last in load order in `banking`, so it will override any selectors of the same specificity from NDS. The scarier, higher risk change is adjusting …

style(reset): add reset and base CSS

---

release.config.js

fixes #520 
This change instructs `semantic-release` to make a patch version release on `style` type commits. The rest of the rules are the defaults, but I am explicitly adding to make it more clear what commit type does what.

build(semantic-release): update release rules

---

src/Tooltip/index.stories.js

fixes #491 
The main `Tooltip` story was showing the component as `<No Display Name />`. This change moves the wrapper div from the decorator to the story template, which fixes the problem.

docs(Tooltip): fix display name in stories

---

src/helper-classes/index.stories.mdx
src/helper-classes/spacing.scss

fixes #440 
Adds spacing helpers based on element axis. For example:
```
margin--y--none
padding--x--s
```

style(helper-classes): add axis based spacing helper classes

---

src/LoadingSkeleton/index.scss

fixes #514 
Adds animated linear gradient to `LoadingSkeleton` lines

style(LoadingSkeleton): add shimmer animation

---

package-lock.json
package.json

Resolves `marked` security issues.
The major version change in `semantic-release` is due to v19 no longer supporting node v15. This is not an issue with NDS, which uses node v16.

build(semantic-release): update semantic-release version

---

src/helper-classes/font.scss
src/helper-classes/index.stories.mdx
tokens/src/font/size.json

fix #508
Adds a design token for the concept of "h0", which is the topmost heading font size in our type scale (`40px`).

feat(typography): add heading0 font size token with helper class

---

src/Dialog/index.js
src/Dialog/index.scss
src/Dialog/index.stories.js

fixes #417 
Updates `Dialog` styling to address design feedback

fix(Dialog): address design feedback

---

src/Pagination/index.js
src/Pagination/index.test.js

fixes #545 
Only render pagination component if `totalPages` is > 1

fix(Pagination): render empty fragment when totalPages is 1

---

src/formatters/formatDate.js
src/formatters/formatDate.test.js
src/formatters/formatNumber.js
src/index.js

fixes https://github.com/narmi/banking/issues/15021
Adds `formatDate` function

feat(formatters): add formatDate utility function

---

src/Tabs/index.js
src/Tabs/index.scss
src/Tabs/index.stories.js

Related:
- https://github.com/narmi/banking/pull/15117/files#diff-72afc0afce8484875275ed7d185ed2eb558b302e8f697a13259afe46b3033ebcR13
Adds `hasBorder` prop to `Tabs`.

feat(Tabs): add `hadBorder` prop to provide border control

---

package-lock.json
package.json
scripts/class-adoption.mjs
scripts/component-adoption.mjs
scripts/util/getHelperClassNames.mjs
scripts/util/ignore-patterns.mjs
src/helper-classes/background.scss
src/helper-classes/font.scss

Adds command `npm run stats:classes <target>` to find all usage of NDS helper classes in a given local dir.
1. the script reads `src/helper-classes` and compiles sass files into CSS
2. the CSS is parsed to get all the class names
3. every valid file in the target directory is searched for all the class names and results are tallied

build(scripts): add class adoption script

---

.github/workflows/jest.yaml
__mocks__/styleMock.js
jest.config.js
src/index.test.js

fixes #560 
A little something to save us from the embarrassment of breaking all exports by making a mistake in `src/index.js`. It's not a full example consumer, but it's better than nothing.
When I recreate the issue we encountered a week or so ago (`module.exports = componentsList`) in the index file, the unit test catches the problem:

test(index): basic example consumer unit test

---

src/helper-classes/index.stories.mdx
src/helper-classes/position.scss
src/index.scss

fixes #441 
Adds `alignChild` helper classes.
`alignChild--<xAlign>--<yAlign>` (follows the same x,y order of `background-position` and other CSS rules)
Right align something:
```jsx
<div className="alignChild--center--right">
<a href="#">Link aligned right and vertically centered within the parent without floats!</a>
</div>
```
Vertically and horizontally center an emoji in a 60px² box:
```jsx
<div style={{ width: '60px', height: '60px' }} className="alignChild--center--center">
<span>😎</span>
</div>
```
Place the emoji in the bottom left of a 60px² box:
```jsx
<div style={{ width: '60px', height: '60px' }} className="alignChild--left--bottom">
<span>😎</span>
</div>
```

style(helper-classes): add child alignment helper classes

---

src/Input/index.js

Adds space to keep us more in line with the style guide 
previous:
new:

fix(Input): add margin between error message icon and text

---

src/Dialog/index.js

I've noticed that clicking outside of the dialog does not close it - I think expected behavior is that such a click event should in fact dismiss it. 
This PR simply adds another `useEffect` hook with a click listener, to detect if a click event target is outside of the dialog content and if it is, close the dialog.

fix(Dialog): close dialog on click outside of content box

---

src/Dialog/index.js

An interesting error occurred where if the click event for a target INSIDE the Dialog caused that element to be unmounted, the Dialog would call `onUserDismiss` and subsequently close.

fix(Dialog): more robustly check if a click event target is not inside the Dialog, before calling dismiss method.

---

src/Tabs/TabsList.js
src/Tabs/TabsPanel.js
src/Tabs/TabsTab.js
src/Tabs/context.js
src/Tabs/index.js
src/Tabs/index.stories.js
src/Tabs/index.test.js

fixes #570 
Adds `selectedIndex` prop that allows consumers to optionally use `Tabs` as a fully controlled component.

feat(Tabs): add `selectedIndex` prop to enable fully controlled Tabs

---

src/helper-classes/background.scss
src/helper-classes/spacing.scss

fixes #495 
Raises specificity of spacing and background color helper classes because...
- When a user applies a class to an element, it should just work
- The expectation for undoing a style rule applied by these classes is to simply remove the class
- The `background-color` property is granular; other background properties can be added as needed
- The spacing helpers give fine grained control enough to use them in combination as needed without needing to override with custom css

fix(helper-classes): important all background color and spacing helpers

---

.storybook/main.js
jest.config.js
src/Button/index.js
src/Button/index.stories.js
src/Button/index.test.js
src/icons/Icons.stories.js
webpack.config.js

fixes #551 
Adds support for prepending or appending an icon to `Button` labels by icon name.
Also adds webpack and jest alias for importing `src` directories.
```jsx
<Button kind="plain" label="Edit Preferences" iconEnd="edit" />
```
```jsx
<Button kind="secondary" label="Do Business" iconStart="briefcase" />
```
```jsx
<Button label="Dock boat randomly" iconStart="anchor" iconEnd="shuffle" />
```

feat(Button): add `startIcon` and `endIcon` props for Button icons

---

src/Pagination/index.js
src/Pagination/index.scss

fixes #558 
- Fix a11y issue with invalid `role` attributes on icons
- Allow page number circles to expand for larger numbers
- Update hover color to subdued 20% theme primary
- Increase chevron size (per design)

fix(Pagination): accommodate large numbers in page styles; address design feedback

---

src/helper-classes/forms.scss
src/helper-classes/index.stories.mdx

fixes #574 
Adds documentation for `button--reset` class

docs(helper-classes): document list reset class

---

src/Popover/index.stories.js

fixes #576 
Fixes code example for `Popover` overview story. The decoarator was obscuring the component props passed through

docs(Popover): fix overview example

---

src/Dialog/index.js

fixes #599 
Changes "click outside" handling to use the shim itself to capture clicks. This works better for Dialogs that contain a portalled element that is not in the DOM tree of Dialog

fix(Dialog): capture click events on shim to close modal

---

src/Tag/index.js
src/Tag/index.scss

fixes #601 
- Changes some colors to use `--theme` colors
- Changes `display` property of the Tag to use `inline-block` so as to avoid auto height/width behavior of a flex
- Uses `Row` to eliminate some extra styles

fix(Tag): make themable; prevent auto height using inline-block display

---

src/helper-classes/position.scss

fixes https://github.com/narmi/banking/issues/16249
This works:
```jsx
className="alignChild--center--center otherClass" 
```
This does **NOT** work:
```jsx
className="otherClass alignChild--center--center" 
```
The base selector for the `alignChild` helpers were using the _begins with_ operator, which assumes the alignChild class is the first class in the class attribute.
The issue is fixed by using the _includes_ operator in the attribute selector.

fix(helper-classes): fix alignChild base selector to apply to any order

---

src/helper-classes/index.stories.mdx
src/helper-classes/spacing.scss

fixes #596 
Adds spacing axis helpers for default spacing. For example, `padding--x` or `margin--y`.

fix(helper-classes): add default space axis helpers

---

src/helper-classes/font.scss
src/helper-classes/index.stories.mdx

fixes #539 
Adds helpers to control text wrapping and truncation. Supports multiline truncation via `line-clamp` because we don't support IE.

feat(helper-classes): add text flow control helpers

---

package-lock.json
package.json

Allows consumers to use React 17 as a peer dependency.
Here's NDS running with React 17 to verify it works: https://codesandbox.io/s/competent-leavitt-4e70pf?file=/src/App.js

fix(peers): allow React 17 as a peer dependency

---

src/Button/index.js
src/Button/index.test.js

fixes #619 
- removes `role="button"` because it's not helpful anchor elements and redundant for button elements
- update tests accordingly
- add (hopefully) helpful note about making anchor elements valid by including an `href` attribute
- force element to always be focusable via tabIndex

fix(Button): remove uncessary role attr; update docs for anchor buttons

---

VENDOR_LISCENSE.md
package-lock.json
package.json
src/Dialog/index.js
src/Dialog/index.stories.js

fixes #359 
Adds focus trap to dialog that prevents keyboard navigation to hidden elements behind the dialog as an accessibility fix

fix(Dialog): add focus trap to prevent focusing hidden elements

---

src/Button/index.scss

fixes #626 
The `kind="secondary"` Button will now mix hover color against white to avoid  the "bleed thru" problem when placed on dark backgrounds:

fix(Button): make secondary hover color consistent in all contexts

---

src/helper-classes/border.scss
src/helper-classes/index.stories.mdx
src/index.scss
tokens/src/border/border.stories.mdx
tokens/src/border/radius.json

fixes #615 
- adds `s` and `l` border radius tokens
- adds border radius token documentation
- adds helper classes for border radius `rounded--<side>(--<amount)`
- adds helper classes for adding borders `border--<side>`
- updates helper classes example in documentation
New token docs:
New helper class docs:
Updated helper classes example:

feat(helper-classes): add border helpers

---

src/Popover/index.js
src/Popover/index.stories.js

fixes #632 
Accessibility enhancement.
When the popover is open, focus is "trapped" in the popover content. This makes it easier to keyboard navigate the contents of a popover.

fix(Popover): add focus trap for a11y

---

src/DropdownTrigger/index.js
src/DropdownTrigger/index.scss
src/DropdownTrigger/index.stories.js
src/DropdownTrigger/index.test.js
src/index.js
src/index.scss

relates to:
- #630 
Part one of accessibility fixes for our dropdowns.
This component is intended to be used as a trigger button for menus, multiselects, selects, and other popovers. It mostly mimics the behavior of a `TextInput` visually, but as a button element.

feat(DropdownTrigger): add component for triggering popovers

---

src/Row/RowItem.js
src/Row/index.js
src/Row/index.stories.js
src/Tabs/index.stories.js

Configure stories to output props tables for sub components like `Row.Item` and `Tabs.Panel`.

docs(storybook): add props tables for subcomponents

---

package-lock.json
package.json
src/Dropdown/index.js
src/Select/SelectAction.js
src/Select/SelectItem.js
src/Select/index.js
src/Select/index.scss
src/Select/index.stories.js
src/Select/index.test.js
src/index.js
src/index.scss

fixes #630 
Add `Select` component and deprecates `Dropdown`. We are going the route toward dropdowns tailored to their specific needs rather than a general purpose component which can not easily be made accessible.
This uses our `DropdownTrigger` in combination with the `downshift` library for managing a11y attributes, keyboard events, and focus.
----
I recommend getting context for these changes by running the branch locally:
```sh
git checkout -t origin/feat/630-select-component
npm install
npm run build
npm run storybook
```

feat(Select): add `Select` component

---

src/Toggle/index.js
src/Toggle/index.scss
src/Toggle/index.stories.js

fixes #542 
Adds some features to `Toggle` for accessibility:
- allow a built-in label via `label` prop
- allow a custom label detached from the `Toggle` via `labelledBy` prop
- set readable button text that is visually hidden
Adds stories for usage examples of labeling a `Toggle`

fix(Toggle): allow accessible labelling of Toggles

---

src/helper-classes/font.scss
src/helper-classes/font.stories.mdx

fixes #646 
Adds missing docs for `whiteSpace` helper classes (truncation)

docs(helper-classes): add whiteSpace class docs

---

src/RadioButtons/index.scss

fixes #634 
When you use `display: none`, the element is fully removed from document flow and the browser treats the element as if it is not in the DOM. Screen readers and keyboard navigation behaves as if the element doesn't exist.
We were hiding the native `input type="radio"` elements using `display: none`. This PR uses some different CSS to visually hide the input without making the element inaccessible to screen readers and keyboard navigation.

fix(RadioButtons): fix keyboard navigation for a11y

---

src/Checkbox/index.scss
src/Checkbox/index.stories.js

fixes #642 
Similar to #648 - when an element is fully hidden with `display: none` _or_ has `0, 0` dimensions, the browser and screen readers treat the element like it doesn't exist, which is why we were missing keyboard navigability on our checkbox component.
The fix is to hide the native input with a CSS technique that only hides it visually.

fix(Checkbox): enable keyboard navigation for a11y

---

src/Tag/index.scss

fixes #637 
- bumps font size to 14px
- fix height of tag to `26px`
- maintain 4px padding on either side

fix(Tag): bump font size; fix height to 26px

---

src/Button/index.js
src/Button/index.scss
src/Button/index.stories.js

fixes #651 
Adds `kind="negative"` to `Button`. This is for use in the ["Component button" pattern](https://zeroheight.com/8ac87d4ba/p/612bfa-button/t/4358c3).

feat(Button): add `kind="negative"` for negating action buttons

---

src/Tabs/TabsList.js
src/Tabs/index.stories.js

fixes #636 
Enables Tabs to be inset in the tabs list by padding the tabs list.
Added `xPadding` prop to `Tabs.TabsList`.

feat(Tabs): add `xPadding` prop to `Tabs.TabsList`

---

src/formatters/formatDate.js

Currently the documentation looks as below, which is not quite correct. For `short` type formatting, years are outputted as two digits.

chore(formatters): minor correction to jsdoc for formatDate function

---

src/Checkbox/index.js
src/Checkbox/index.scss
src/Checkbox/index.stories.js
src/Checkbox/index.test.js

related to:
#616 
Adds a card style variant to our `Checkbox` component. Internal state was necessary to support visual feedback for focus states when navigating via keyboard.
https://user-images.githubusercontent.com/231252/161630812-46af669b-3f20-48cb-a1c1-e5df0ae0bcad.mp4

feat(Checkbox): add `card` variant

---

README.md
package.json

fixes #640 
Adds `npm run dev` which does an npm install, build, watch, and storybook in a tmux session.

build: add command to run storybook + watch

---

src/Select/index.js
src/Select/index.stories.js
src/Select/index.test.js

fixes #580 
Adds `value` prop to `Select` to enable a fully controlled mode.

feat(Select): add `value` prop to enable fully controlled mode

---

src/Dialog/index.scss
src/Select/index.scss
src/Select/index.stories.js

fixes #641 
Added some minor style tweaks and story example for a `Select` inside a `Dialog`.  
Basically, if there's room, it will just open normally. If there's not enough room under the `Select` for its dropdown, the parent container will grow to fit it.
This isn't my favorite option visually, but it did turn out to be the best option to preserve accessibility of the focus trap in the Dialog.
https://user-images.githubusercontent.com/231252/162219871-36c1c1dd-edfb-451e-8ebf-1cb70d55acad.mp4

fix(Select): minor style fixes; show example in Dialog

---

.eslintrc.js
src/Card/index.stories.js
src/Row/index.stories.js
src/SeparatorList/index.stories.js

relates to:
- #482 
enable `jsx-a11y/anchor-is-valid` lint rule

refactor: enable `jsx-a11y/anchor-is-valid` lint rule

---

.eslintrc.js
src/Button/index.js
src/Dropdown/index.js
src/Dropdown/index.stories.js
src/Input/index.js
src/PlainButton/index.js
src/Row/RowItem.js
src/Row/index.js
src/Row/index.stories.js
src/Select/index.js
src/Select/index.stories.js
src/SeparatorList/index.js
src/SeparatorList/index.stories.js
src/SeparatorList/index.test.js
src/TextInput/index.js
src/icons/Icons.stories.js
src/util/AsElement.js

relates to:
- #482 
Enable `react/jsx-key` and `react/prop-types` lint rules.

refactor: enable `jsx-key` and `prop-types` react lint rules

---

.eslintrc.js
src/Toggle/index.stories.js

relates to:
- #482 
Enable rule and suppress false error in Toggle story

refactor: enable `label-has-associated-control` lint rule

---

src/Tag/index.js
src/Tag/index.scss
src/Tag/index.stories.js

fixes #683 
Match variants to figma designs.

fix(Tag): adjust sizes on variants

---

.eslintrc.js
src/ContentCard/index.js
src/Dialog/index.js
src/Input/index.js
src/Modal/index.js
src/Pagination/index.js

fixes #482 
Enable all remaining lint rules (mostly about static element roles and click events having keyboard events)

refactor: enable all remaining disabled lint rules

---

src/Tooltip/index.js

fixes #697 
- Fixes the issue where `maxWidth` default and/or prop passed in was having no effect on the Tooltip
- Sets default max width to `400px`

fix(Tooltip): fix `maxWidth` prop

---

src/formatters/formatNumber.js

Partially address https://github.com/narmi/banking/issues/18403
Adds support to older browsers who do not support the `narrowSymbol` as a currencyDisplay option in the Int.NumberFormat (https://caniuse.com/?search=currencyDisplay)

fix(numberformat): Catch error in case of browser unsupported currency format

---

src/Checkbox/index.scss
src/RadioButtons/index.scss

related to: https://github.com/orgs/narmi/projects/5/views/13
The `RadioButtons` and `Checkbox` components should just inherit the default font size, but we're finding we must set them explicitly to work around legacy CSS in `banking` overriding the property

fix(RadioButtons/Checkbox): explicitly set font size

---

src/Input/index.scss

fixes https://github.com/narmi/banking/issues/17201
Prevent long unbroken lines of text in a textarea from exceeding the bounds of its parent box.

fix(TextInput): enable horizontal scrolling for long unbroken lines

---

src/Input/index.js
src/TextInput/index.js
src/TextInput/index.stories.js

fixes #197
fixes #713 
Support icon in `TextInput`. 
Our underlying `Input` component already supported this, so it was just a matter of adding a prop with the proper validation on `TextInput`.

feat(TextInput): add icon support to TextInput

---

src/ContentCard/index.scss
src/ContentCard/index.stories.js

fixes #705 
- make default `ContentCard` background white instead of transparent
- clean up story for interactive `ContentCard`

fix(ContentCard): update styles to match design specs

---

src/Select/index.js

relates to #712 
As it turns out, the `child.type` property isn't totally reliable across React 16-17 and between client side and server side rendering.
This PR changes the children filtering behavior in `Select` to use the more reliable `props` object to detect if its children are valid `Select.Item` or `Select.Action` components.

fix(Select): fix children filtering for SSR & React 17

---

src/DropdownTrigger/index.scss
src/Select/index.js
src/Select/index.scss
src/Select/index.stories.js
src/index.scss

fixes #703 
- Moves helper classes above component-specific styles. This **will not** affect consumers of NDS, but does allow component-specific CSS to override any helper classes applied to NDS components. This is probably the way it should have been from the beginning.
- Make the chevron from `DropdownTrigger` float above any dropdowns or popovers per design
- When an item in `Select` is selected, add a gutter to menu items and show a checkbox on the selected item

feat(Select): add checkmark to selected item in menu list

---

src/RadioButtons/index.js
src/RadioButtons/index.stories.js

fixes #727 
Allows `RadioButtons` to be fully controlled when a `value` prop is passed.

feat(RadioButtons): set fully controlled mode when  prop is passed

---

src/Button/index.js
src/Button/index.scss

fixes #725 
Restricts text decoration effects to the label area of button (instead of extending to the icon areas, which looks weird)

fix(Button): restrict hover underlines to text label

---

src/helper-classes/spacing.scss
src/helper-classes/spacing.stories.mdx
tokens/src/layout/space.json

Design specs sometimes ask for a spacing of `60px` which for now we hardcode or define as a var in the NDS consumer. It's come up often enough for me to think that it should be made part of the standard.

feat(helper-classes): add xxl spacing size

---

src/Button/index.scss
src/Card/index.scss
src/Checkbox/index.scss
src/DateInput/index.scss
src/Input/index.scss
src/Modal/index.scss
src/RadioButtons/index.scss

fixes #731
fixes #732
Some NDS style values were being set to a legacy CSS custom property for the primary theme color. These get appropriately shimmed in `banking` and storybook, but third party consumers are missing the shim.
This PR replaces all the legacy vars with the correct `--theme` var from design tokens to resolve the problem of vanishing borders and unchecked radios.

fix: update unshimmed legacy theme vars

---

src/icons/icons.css
webpack.config.js

fixes #741 
fixes #739 
- converts icon font file `url()` to inline base64
- load only the `woff` format for icon fonts to reduce CSS size (we don't support IE)
Next.js consumers were running into an issue in production builds where icon font files could not be loaded due to a CORS error. We can sidestep the issue by inlining the icon font until there is a more stable fix.
We will look for a better long-term solution in the follow a ticket: #746

fix(icons): inline icon assets

---

src/Card/index.scss
src/Checkbox/index.scss
src/DateInput/index.scss
src/Dropdown/index.scss
src/Input/index.scss
src/Modal/index.js
src/Modal/index.scss
src/RadioButtons/index.scss
src/base-styles/typography.scss

fixes #749 
Replaces all usage of older `--nds-` CSS vars with standard vars from design tokens. This ensures nothing in NDS relies on the consumer to shim these properties.

refactor(tokens): replace all legacy `--nds-` tokens with standard vars

---

src/Dialog/index.scss
src/Tabs/index.scss

fixes #758 
- Make selected tab have bold font weight
- Use 8px border radius on `Dialog`

fix: minor styling tweaks for `Tabs` and `Dialog`

---

src/Toggle/index.js
src/Toggle/index.stories.js
src/Toggle/index.test.js

fixes #771 
Makes `Toggle` have a fully controlled mode via the new `isActive` prop.

feat(Toggle): add `isActive` prop to `Toggle` (fully controlled)

---

src/Pagination/index.scss

relates to:
- https://github.com/narmi/banking/issues/20189
Per design, page numbers should be the primary text color

fix(Pagination): fix unselected page number color

---

src/Input/index.scss

fixes #766 
The white background is defined in the parent box of the input, so we can make the input itself transparent to prevent cutting off text in the floating label

fix(TextInput): prevent descenders in floating label from being cut off

---

src/helper-classes/font.scss
tokens/src/font/size.json

Design has asked for info tooltip icons to be 10px, this adds an NDS font size + class for that purpose.

feat(fonts): add xxs font size (and helper class)

---

src/Button/index.js
src/Button/index.scss
src/Button/index.stories.js
src/Button/index.test.js

fixes #779 
Adds `size` prop to `Button`.

feat(Button): add `size` prop to support size variants

---

src/RadioButtons/index.js
src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

fixes #775 
Adds `error` prop to `RadioButtons`

feat(RadioButtons): add `error` prop to support RadioButtons error state

---

src/Combobox/index.js
src/Combobox/index.stories.js
src/Combobox/index.test.js

fixes #778 
Allows the input inside `Combobox` to be fully controlled. Addresses an issue Grasshopper found where the input was blank after rerendering in their application.

feat(Combobox): add `inputValue` prop to enable fully controlled input

---

src/DropdownTrigger/index.js

The `button` element in the DropdownTrigger component does not have a `type` specified, which means that when it is a child of a `form`, it will submit the form. This PR sets the `type` to `button` to prevent this behavior.

fix(DropdownTrigger): set `type` attribute on button element

---

.github/workflows/release.yaml

Only CI should run the release workflow. This removes the manual trigger for the workflow.

build(ci): remove manual trigger from release workflow

---

src/Select/index.js
src/Select/index.stories.js
src/Select/index.test.js

fixes #793 
Fixes errors thrown when `value` is passed, but with a value of `undefined`, `null`, or `""`.
Basically, the component uses `value` to look for a matching `Select.Item` by its `value` prop. If the item is not found in children, the Selection should clear. There were a few places where the code assumed an item would always be present and have props.

fix(Select): cover deselection case in controlled mode

---

src/Input/index.scss

closes https://github.com/narmi/banking/issues/20407
The form styling issue we saw on an iphone 11 / iOS 15 was due to default styling of browser autofill. This change ensures that no background is placed behind an autofill value, preventing an autofilled value from covering up the floating label of TextInput.
Also applies to any component that uses TextInput (like DateInput)

fix(TextInput): ensure autofill styling doesn't overlap floating label

---

src/RadioButtons/index.scss

fixes #796 
Makes radio button backgrounds white. Useful for placing radio buttons on a dark background.

fix(RadioButtons): set radio backgrounds to white

---

src/Tooltip/index.js

fixes #801 
Allows `Tooltip` to render server side without errors by removing the `container` option from the `useLayer` hook. As it turns out `document.body` is the default container it attaches to and we do not need to specify this option.

fix(Tooltip): allow SSR by using default `container` option of `useLayer`

---

src/TruncatedAccount/index.js

fixes #800 
Adds a `title` attribute with the full account name. Useful to users who navigate desktop web with a mouse

fix(TruncatedAccount): show full account name in `title` on hover

---

src/helper-classes/background.scss
src/helper-classes/font.scss

fixes #750 
Adds theme color variants for font and background color helper classes.
(e.g. `fontColor--theme--primary`)

feat(helper-casses): add theme color variants for fontColor and bgColor

---

.storybook/preview.js
src/Button/index.stories.js
src/Card/index.stories.js
src/Checkbox/index.stories.js
src/Combobox/index.stories.js
src/ContentCard/index.stories.js
src/DateInput/index.stories.js
src/Dialog/index.stories.js
src/Dropdown/index.stories.js
src/LoadingShim/index.stories.js
src/Pagination/index.stories.js
src/Popover/index.stories.js
src/RadioButtons/index.stories.js
src/Row/index.stories.js
src/Select/index.stories.js
src/SeparatorList/index.stories.js
src/Tabs/index.stories.js
src/TextInput/index.stories.js
src/Toggle/index.stories.js
src/Tooltip/index.stories.js

fixes #791 
Moves some story-level configuration to the global config file:
- Actions should fire on any prop starting with `on`
- Controls for `children` prop should always be disabled in the props tables

docs(storybook): set actions and children control settings globally

---

src/RadioButtons/index.scss

I've checked out usages of these in banking, and this will actually fix minor spacing bugs there (on the TFA verification pages for example).

fix(RadioButtons): don't show bottom margin on last radio button option

---

src/Input/index.scss

fixes #812 
It looks like in some circumstances, inputs without a floating label were changing height once they have a value. This fix prevents the input from shrinking in height.

fix(TextInput): prevent global CSS from modifying input height

---

src/Dialog/index.stories.js

fixes #811 
**Only updates documentation**
- add padding to popover options
- add user dismissal handler to dialog so it closes on "x" click, clicking outside, or Esc key

docs(Dialog): add user dismissal handler to popover dialog story

---

src/TextInput/index.js

closes #821 
relates to: https://github.com/narmi/banking/issues/23322
- Add `aria-label` property to input element generated by `TextInput`
Our accessibility tool in Storybook did not find this violation, but different assistive technologies have different needs. Sometimes they will not be able to associate the `label` element we output to the `input` element, so this aria property ensures the label is _always_ readable, regardless of the position and visibility of the `label` element.

fix(TextInput): add `aria-label` property as a11y fallback

---

src/Checkbox/index.js
src/Checkbox/index.scss

Changed the fragment to a `div` to add the `.nds-checkbox-container` classname. This is because there is a margin beneath `.nds-checkbox` label, but if an error is displayed beneath that label, we want that margin below the error.

feat(Checkbox): add error prop to display error beneath checkbox

---

src/Checkbox/index.js
src/RadioButtons/index.js

fixes #846 
Addresses an issue we keep seeing in `banking` where the `Checkbox` and `RadioButtons` labels are bolded (probably from a semantic-ui selector).
- Remove `nds-typography` class (no longer needed as we set the type defaults in base styles)
- Add `fontWeight--default` helper to both components, because helpers apply an `!important`

fix(Checkbox,RadioButtons): specify label font weights

---

src/Checkbox/index.scss

closes #850 
- Simplifies CSS for the `normal` variant of `Checkbox`
- Match borders to the figma designs for unchecked, checked, and hover
- Add a focus ring to a focused checkbox to make it easier to see which box is focused when they're already checked

fix(Checkbox): correct styling for hover and focus states

---

src/Drawer/index.scss
src/Drawer/index.stories.js

The z-index in the Drawer was within the same range of Popover and other NDS elements that rely on the z-index to appear on top of other elements. This caused those elements to be unusable within the Drawer.
This PR decreases the z-index range for the Drawer, which allows elements like the Popover to be used within it.
https://user-images.githubusercontent.com/40327446/214100866-06c2e020-c5c6-42a9-a018-2179a22cc51e.mov

feat(Drawer): allow popovers within Drawer

---

src/ContentCard/index.scss

fixes #899 
Adds an extra pixel of thickness to selected cards, without increasing width or height

fix(ContentCard): thicken border of selected interactive card

---

src/DropdownTrigger/index.scss

closes #898 
Prevent the chevron in closed Select triggers from overlapping open Select popovers

fix(Select): prevent chevron from overlapping other open popovers

---

src/DropdownTrigger/index.js
src/DropdownTrigger/index.scss

closes #907 
Prevents selected value in `DropdownTrigger` from showing as blue in iOS 
See also: <https://developer.apple.com/forums/thread/690529>

fix(DropdownTrigger): set explicit text color for value

---

src/Checkbox/index.scss
src/RadioButtons/index.scss

fixes #909 
Updates `card` variants of Checkbox and RadioButtons to always use bold text per design

fix: RadioButtons and Checkbox card kinds use bold text

---

src/Dialog/index.scss

fixes #862 
Ensure space between content and footer area is consistent by removing min-height.

fix(Dialog): remove min-height of dialog

---

src/Popover/index.js

fixes: https://github.com/narmi/banking/issues/29051
Instead of attaching the Enter key event to window, use only the trigger to intercept that event. Escape still works to close the popover if it's open.

fix(Popover): only open with Enter key on trigger event

---

src/Button/index.scss

Before
After
Mocks: https://www.figma.com/file/49YCj4HK9QE93A0hcBmJHV/Master-Style-Guide?node-id=14-171&t=wDn2JBozpp9VOFyS-0
Discovered in https://github.com/narmi/banking/issues/29802

fix(Button): increase button border radius size on mobile

---

src/base-styles/defaults.scss

fixes #921 
Changes underline text decoration behavior globally so that "ink" (descenders) don't interrupt the underline.
**This will not add underlines to any elements.** This rule only changes the style of an underline when that text decoration property is present.
(per design: <https://www.notion.so/narmi/First-IB-Design-QA-f751c057241e4031a9e9db636c2a6dba?pvs=4#1eded13c12904981995592ead26a5ee4>)

fix(base-styles): skip ink on text underline globally

---

src/Input/index.scss

Fixes https://github.com/narmi/banking/issues/30236
Fixes broken selector for input placeholders
**Before** (user agent default)
**After** (NDS medium grey)

fix(TextInput): fix placeholder color

---

src/icons/style.css
webpack.config.js

Fixes issue where prod builds of Nextjs were not fetching icomoon font assets correctly, resulting in CORS errors.
This webpack change causes the `woff` referenced in `src/icons/style.css` to be inlined as base64, working around the fetch entirely until we solve this problem in a more long term way.

feat(icons): inline icon font asset

---

package-lock.json
package.json

closes #845 
Verified working in a latest NextJs consumer (which uses React 18).
In source, NDS still uses React 16. The built files in _dist_ may be used by React 18 consumers. This allows third party developers to use the latest version of their favorite framework with NDS.
Upgrading _source_ in NDS to React 18 is a much bigger lift we can do later.

feat: Support React 18 consumers

---

src/deprecations.json
src/index.scss
webpack.config.js

relates to https://github.com/narmi/banking/issues/15579
Adds a `deprecations.json` to `dist/` that lists important deprecations (things that will be removed in the next major version).
- a step toward a more automated deprecation strategy for NDS
- serves as a deprecation list for dangerfile rules in internal Narmi software

fix(dist): add deprecations json to `dist/`

---

src/ContentCard/index.js
src/ContentCard/index.stories.js

closes #720
Removes deprecated `type` prop from `ContentCard`. Use `kind` moving forward.
**Targets `release/v3` branch**

refactor(ContentCard)!: remove deprecated `type` prop

---

src/Tooltip/index.js
src/Tooltip/index.stories.js
src/Tooltip/index.test.js

This allows the `Tooltip` component to be a controlled component which is needed for https://github.com/narmi/banking/issues/33260.
A developer can pass an optional `isOpen` property to control if the `Tooltip` is open or not.

Add option for Tooltip component to be controlled with isOpen prop

---

src/Button/index.js

closes #946 
Set the `type` attribute default of the root element of `Button` to `button`.
This prevents the html default behavior of a `button` being a `submit` button, which will fire a submit event and register a click when a user presses the Enter key while within a `form` element.

fix(Button)!: set default type attribute as 'button'

---

src/Checkbox/index.scss

closes #878 
**Targets `releases/v3`**
Instead of adding a margin to every checkbox container, which will create a spacing side effect with the element directly below the component, this PR makes checkbox spacing automatically appear between checkboxes based on if they directly follow each other in the DOM.

refactor(Checkbox)!: use auto spacing between checkboxes

---

src/LoadingShim/index.scss

fix(LoadingShim): make loading visual smaller

---

src/TextInput/index.js
src/TextInput/index.stories.js

Without this, TextInput fields that have an onChange won't have it triggered when the input is cleared:
https://github.com/narmi/design_system/assets/40327446/a8989951-8db7-4d5c-999c-821fe111ca13
However, it should, since it should be the same thing as manually deleting the text. Example:
https://github.com/narmi/design_system/assets/40327446/3024635e-3727-48ac-b330-086ba57e6598

fix(TextInput): make clearInput call onChange

---

src/Popover/index.js
src/Popover/index.stories.js

closes #935 
Adds `alignment` prop to `Popover`. This prop is passed through to the positioning engine to allow us to not only pick a side, but an _alignment_ for the popover.
`<Popover side="top" alignment="start" ...otherProps />`

feat(Popover): add alignment prop for more position control

---

src/Tabs/TabsTab.js
src/Tabs/index.test.js

The parent `tablist` role must have `tabs` as children.
For https://github.com/narmi/banking/issues/32272

fix(tabs): lift aria role for tabs up

---

package-lock.json
package.json
src/DateInput/index.js

Part of https://github.com/narmi/banking/issues/32271

fix(DatePicker): Android mobile datepicker doesn't like backspace

---

package-lock.json
package.json
src/Dialog/index.js
src/DropdownTrigger/index.js
src/DropdownTrigger/index.scss
src/Popover/index.js
src/Select/index.js
src/Select/index.scss

closes #949 
- Replaces focus trap library with `react-focus-lock`, which is a better implementation that can follow portals
- Adds "active' state for dropdown trigger used in `Select`
- Replace static CSS positioning in `Select` with the `react-laag` positioning hook (also used in `Popover`)

refactor(Select): use portalled dropdown

---

CHANGELOG.md

Forces semantic-version to bump the patch version for this Select fix that already merged (with type `refactor` by mistake)

fix(Select): use portalled popover element

---

src/fonts/fonts.css
src/helper-classes/font.scss
tokens/src/font/color.json
tokens/src/font/weight.json

closes #967 
- Darkens secondary font color to meet AA contrast guidelines for text 14px and under
- Change Mullish font to a [variable font](https://fonts.google.com/knowledge/introducing_type/introducing_variable_fonts), which gives us all weights in one download roughly the size of a single weight
- Add design token and helper class for `200` weight Mullish ("thin")

feat(Typography): darken secondary text; add thin Mullish weight

---

src/Dialog/index.js
src/Popover/index.js

Disables `autoFocus` feature of `FocusLock` everywhere in NDS it's used. Autofocusing the first element can lead to a frustrating experience for users, especially in regard to a11y

fix(focus traps): diable autofocus in Popover and Dialog

---

src/Pagination/index.js
src/Pagination/index.stories.js

closes #984 
Refactor `Pagination` to allow fully controlled selected page and total pages.
When the selected page becomes out of bounds (most likely because total pages change), we move selection back to the beginning. If the currently selected page is within bounds, we keep that page selected.

feat(Pagination): enable fully controlled mode

---

src/Select/SelectCategory.js
src/Select/SelectItem.js
src/Select/index.js
src/Select/index.scss
src/Select/index.stories.js
src/Select/index.test.js
src/base-styles/reset.scss

closes #936 
Adds a `Select.Category` grouping element for select items.
The actual select items are treated by downshift as a flat list of items, but the component has some helpers to determine which items are in which category so we can open and close the disclosures as the highlight/selection moves through them.
Also made some markup changes to ensure we're not invalidly nesting list items directly inside a `details` element.
The opening and closing disclosures for the categories use the [native `details` html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). This behaves in an uncontrolled manner, but if certain conditions are met (highlighted item is in category or selected item is in category), we force it open using its `open` attribute.
Aside from …

feat(Select): add category grouping feature

---

src/Dialog/index.js

closes #1002 
As part of the NDS v3 release, we refactored some components in `banking` that were using the deprecated `Modal` component. The `Modal` component was providing some bottom spacing to the content area. In `Dialog`, the `footer` prop causes some bottom padding to be added.
**This PR will add some default bottom padding to `Dialog` when no `footer` prop is passed in.**
After the change, `Dialog` usage without a footer will have bottom spacing

fix(Dialog): add bottom spacing when no footer is passed in

---

src/DropdownTrigger/index.scss

resolves https://github.com/narmi/banking/issues/34975
This issue only occurs when `Select` is used and is resolved by removing the z-index. Confirmed via storybook at the expected behavior of the chevron-down in the select box is maintained.

fix(DropdownTrigger): remove z-index on chevron-down

---

src/Dialog/index.js
src/Dialog/index.scss

Identified by @xiexiewenting, the inline `width` style was overriding small viewport behavior because it's higher specificity.
Changing the prop or its default would be considered a breaking change, so we need a way to prevent the `width` prop from setting Dialog width at viewports "s" or smaller.
Instead of directly setting the `width` style property on the Dialog element, we can instead set a _custom property_ that holds the value passed into the component.
This allows us to use CSS to decide when that property value should be used (only on screens larger than "s").
Despite having a `var()` function, CSS doesn't have variables. CSS has _custom properties_, which cascade like any other CSS property. Just like `font-size`, the value of a custom property gets inherited through the DOM tree …

fix(Dialog): prevent width prop from overriding mobile viewport behavior

---

src/Popover/index.stories.js

closes #1007 
Update Popover stories to use correct props on the `Button` component passed in.
When an NDS `Button` is used as a trigger, it takes on `type="button"` by default. When in a form, it implicitly becomes `type="submit"`, which causes some unusual side effects with the Enter key opening the popover.
The docs now reflect how to best avoid this behavior by explicitly setting the button `type`

fix(docs): update popover stories to use type button

---

src/Popover/index.js

fixes #1011 
Avoid referencing document properties without checking if we're in SSR first

fix(Popover): check if SSR in useLayer options

---

src/Popover/index.js

relates to #1011 
Use `typeof` for undefined check

fix(Popover): use typeof for SSR check

---

src/Select/index.js

relates to: 
- https://github.com/narmi/banking/issues/35868
Add key event handling to menu trigger in addition to the menu. This allows users to tab to the field and begin typing before the menu is open. Typing anything with the trigger focused will open the menu.
Once an item is selected, we do not clear it from the display value, but the user may type in the background to autocomplete to another item. This mimics the behavior of a native `select` element.

fix(Select): enable typing in faux input before menu is open

---

src/DateInput/index.js
src/DateInput/index.stories.js

fixes #1010 
Adds `disablePortal` prop to `DateInput` to append the calendar _inside_ its parent instead of `document.body`. This is useful when we want to use a `DateInput` inside a `Popover`.

feat(DateInput): add `disablePortal` for use inside popover

---

src/Select/index.js

**tl;dr** the state reducer in Select didn't work in prod builds. This makes it work in prod builds.
We were hard coding the string value of state change types from the `useSelect` downshift hook. It works fine in dev, but these strings are subject to change in prod builds, so we must instead use the references provided by `useSelect.stateChangeTypes`

fix(Select): use correct state change types in state reducer

---

src/Combobox/ComboboxCategory.js
src/Combobox/ComboboxItem.js
src/Combobox/index.js
src/Combobox/index.scss
src/Combobox/index.stories.js
src/Combobox/index.test.js
src/Select/index.stories.js

closes #1018 
**blocked by: https://github.com/narmi/design_system/pull/1023**
Adds `Combobox.Category` support, similar to the category feature in `Select`.
When categories are passed into `Combobox`, we extract all the children as a flat list, [similar to `Select`](https://github.com/narmi/design_system/blob/a6f155ba42c9d1edb087b326b35b582487be78c1/src/Select/index.js#L129). This allows the downshift `useCombobox` hook to ignore categories and behave the same as a basic Combobox.
Categories are used to nest items inside `details` elements when rendering, [similar to how it works in `Select`](https://github.com/narmi/design_system/blob/a6f155ba42c9d1edb087b326b35b582487be78c1/src/Select/index.js#L282).
A category is only rendered when:
- It has at least one item that has not been …

feat(Combobox): add categories feature 

---

src/Combobox/index.js

fixes #1034 
Renders string from `errorText` prop as an error _outside_ the positioning ref, preventing the dropdown from being offset from the input

fix(Combobox): render error outside of positioning ref for dropdown

---

src/DateInput/index.js
src/DateInput/index.stories.js

fixes #1038 
Convert `input` to `TextInput` to ensure stable label rendering behavior

fix(DateInput): use TextInput component instead of native input directly

---

src/Combobox/index.scss
src/Select/index.scss
src/Select/index.stories.js

resolves: #1045
The `<div id="layers"></div>`, created by `react-laag`, is used alongside `downshift` to build our `Select` component. This `div` is appended to the end of the `body`. Meanwhile, the `Dialog` component also positions itself at the `body`'s end dynamically. As a result, the layers `div`, which has a `z-index` of `3`, precedes the `Dialog` in stacking order.
This PR bumps the `Select` and `Combobox` `z-index`es to 4.

fix(Combobox, Select): Fix Select and Combobox rendering in Dialogs

---

src/Combobox/index.js
src/Combobox/index.scss
src/Input/index.js
src/Input/index.scss
src/Select/index.scss
src/TextInput/index.js
src/TextInput/index.stories.js

closes #1044 
- Adds `startContent` and `endContent` to `TextInput`
- Add story for start and end content props in `TextInput`
- Update category chevron styling in `Select` and `Combobox`
- Update `Combobox` to use `endContent` to render a darker chevron

feat(TextInput): add startContent and endContent props for custom icons

---

src/Dialog/index.js
src/Dialog/index.scss
src/Dialog/index.stories.js

Adds banner as a header style, which looks like this:
https://github.com/narmi/design_system/assets/40327446/0a5dd878-2c5f-4a22-8509-4cf152b31335
For now, the color for text and the `x` icon is hardcoded to white, following the logic on Button.

feat(Dialog): add `banner` header style

---

src/Tag/index.js
src/Tag/index.scss

Fixes issue where label text could overflow the Tag.
Now the tag will grow as large as the parent container allows, and truncate the label text with ellipsis after that.

fix(Tag): prevent label overflow

---

src/Row/index.scss

This allows content to overflow if it sets `overflow` and has no effect if the content has an intrinsic width (most other cases).
For https://github.com/narmi/banking/issues/38767

fix(row): set min-width on Row.Item

---

src/MenuButton/index.js
src/MenuButton/index.scss

closes #1078
Show hover effect on icon trigger when the menu in `MenuButton` is open.
This does not apply to cases where a custom `trigger` is passed in, which is okay because we have the option to show the standard up/down chevron dropdown indicator in custom triggers.

fix(MenuButton): use hover effect on icon trigger when menu is open

---

src/Alert/index.jsx
src/Alert/index.scss
src/Alert/index.stories.js
src/index.js
src/index.scss

closes #1082 
Adds `Alert` component for rendering system messages within document flow. Has an `aria-live` region built in.

feat(Alert): add Alert component

---

src/MenuButton/index.scss
src/base-styles/reach-ui.scss
src/index.scss

fixes #1080
Components that use the ReachUI library for accessibility uses [their custom Portal component](https://reach.tech/portal) when portalling is needed. The ReachUI `Portal` component creates a custom element, `<reach-portal>` and appends it to `document.body`.
The problem is that the `reach-portal` is a different stacking context than `document.body`, where all other portalled elements in NDS are appended to.
This PR creates a global rule that sets the `reach-portal` to a z-index value that is high enough to resolve above the `document.body` stacking context.
In the future, we may want to consider refactoring all components to write to the `<reach-portal>` element instead by using the Reach `<Portal>` component.

fix(MenuButton): set default z-index for reach-ui portals

---

src/Checkbox/index.js
src/Checkbox/index.scss

closes #895 
- Move spacing responsibility from `p` tag to stable containers (it wasn't working when a `markdownLabel` was passed anyway)
- Use document flow positioning for the checkbox check that gets rendered instead of absolute positioning
- Align the checkbox to the top and line up the check icon baseline with the text baseline

fix(Checkbox): fix top alignment for multiline labels

---

src/Dialog/index.scss

closes #1087 
CSS vocab:
```scss
property: value; // the pair is a "rule"
```
When a CSS ruleset has two different rules with the same property name, it will use the cascade (source order) to resolve the conflict. Browsers ignore rules that have properties or values they don't understand, so older browsers will just fall back to `100vh` in this case.

fix(Dialog): prevent mobile chrome from overlapping dialog footer

---

src/Input/index.js

Currently the `startContent` property for text inputs is not rendering correctly because the variable not wrapped in `{}` 
Returning:
```
<div>startContent</div>
```

fix(TextInput): Fix start content property for text input

---

src/Dialog/index.js
src/Dialog/index.scss
src/Dialog/index.stories.js

closes #1098 
Adds a pinned content zone to Dialog near the header that can accept an `Alert` or any other JSX content

feat(Dialog): add notification content slot

---

src/formatters/formatNumber.js
src/formatters/formatNumber.test.js

Some designs call for not showing cents on currency (such as when displaying limits), so it would be useful to have this option in the NDS `numberFormat` method. 
Unfortunately, adding this means if I want to set the `showCents` option, I have to specify the `signDisplay`, even if I just want to use the default. Potential options include:
- allow for falsey value for `signDisplay`, which would mean use the default 
- refactor the optional params in this function to be a single param of object type

feat(numberFormat): add option to not show cents on currency

---

src/MenuButton/index.js

Fixes this issue reported by @JohnathanWeisner

fix(MenuButton): prevent popover from closing before selection callback

---

src/TextInput/index.stories.js

closes #824 
Adds storybook story to show how to build a password input with show/hide feature

docs(TextInput): add example of hide/show password

---

src/helper-classes/position.scss
src/helper-classes/position.stories.mdx

Adds rotation helper classes you can use on any element. Built for rotating icons, but it may come in handy for other things.

feat(helper-classes): add rotation helpers

---

src/Checkbox/index.js
src/Checkbox/index.scss
src/Checkbox/index.stories.js
src/Checkbox/index.test.js

Permits checkboxes to be rendered as indeterminate by passing `indeterminate`.

feat(checkbox): add indeterminate state property

---

src/Popover/index.js
src/Popover/index.stories.js
src/Popover/index.test.js

Allows `Popover` to accept `isOpen` and `onUserDismiss`, following the same pattern as `Dialog` and `Tooltip`.

feat(popover): allow popover to be controlled

---

src/Dialog/index.js

closes #1126 
Firefox is off by one when calculating `scrollHeight`, causing our overflow detector to always return `true` in Firefox. This means that all dialogs in Firefox had the scroll indicator gradient covering up some of the content.
This fix adds a threshold for the clientHeight/scrollHeight math that prevents Firefox from treating short dialogs as scrollable.
One way to ensure the correct value is read is to cause a quick reflow by setting the CSS `overflow-y` value, reading scrollHeight, and then changing overflow back to `visible`. This causes another reflow, so I'd rather just pad the math.

fix(Dialog): prevent misplaced scroll gradient in firefox

---

src/Drawer/index.js
src/Drawer/index.stories.js

Adds support for a render function children in `Drawer`. This allows content inside the drawer to be rendered on-demand and destroyed when the drawer is closed. Notably, such behavior cannot be accomplished by conditioning on `isOpen` because `isOpen` would destroy the contents too quickly and we want to wait until the drawer is fully closed.
See storybook example for a more descriptive demonstration.

feat(drawer): allow children to be a render function

---

src/Alert/index.jsx
src/Alert/index.scss
tokens/src/color/system.json

New designs for fednow require additional customization of the alert component. 
Designs: https://www.figma.com/file/TG6rH21v231JFcZy9jaIz6/fednow-manager?type=design&node-id=1101-2&mode=design&t=942hC19EsHzktDbo-0
Dev storybook:

feat(alert): Customizable icon and new alert kind

---

src/Drawer/index.js
src/Drawer/index.stories.js

Adds a parameter to allow for creating a drawer that does not render the close button.

feat(drawer): allow the close button to be hidden

---

src/Tag/index.js

Allow all kinds of tags to be dismissible. Still backwards compatible with the `dismissible` kind, but added a note that its deprecated to the description.

feat(tag): Support dismissable tag behavior for all kinds

---

.github/dependabot.yml

Enables weekly [dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday) to occur every Sunday. By default, this will create up to 5 pull requests each week as long as there are not already 5 open dependabot PRs.

chore: Add weekly dependabot dependency updates

---

src/IconButton/index.js

I'd like to allow IconButtons to control whether the underlying `<button>` is of type "button" vs "submit" vs "reset".

feat(IconButton): allow passing type to IconButton

---

src/Popover/index.js

resolves https://github.com/narmi/banking/issues/43694
If a Popover is inside another component, like a tab or a summary, interacting with the Popover will also interact with the parent. Calling a stopPropagation() on the events that we handle in this component should prevent this bubbling.

fix(Popover): don't bubble up the user events that we handle

---

src/Drawer/index.js
src/Drawer/index.scss

closes #1132
- For mobile screen sizes, renders a full screen width drawer & moves controls to the top of the drawer

feat(Drawer): use takeover drawer for mobile sized screens

---

src/RadioButtons/index.js
src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

resolves: #1153
This update adds details to the options property for the `RadioButtons` component.

feat(RadioButtons): Add details to the RadioButtons component

---

src/RadioButtons/index.scss

Subtle, but the background color of the whole card isn't white. We need to fix that.
Cleaned up the transitions a little.

fix(RadioButtons): Background color and transition fix for RadioButtons

---

src/RadioButtons/index.js

If a consumer of the component passed in a boolean then the ducktyping would try to destructure it.
This explicitly checks to see if what is being passed is an object.

fix(RadioButtons): Fix duck-typing for radio buttons options

---

src/MenuButton/index.js

Clicking on the trigger itself doesn't seem to be caught by `useLayer()`. Updates the logic so `Menu` respects any `onMenuChange` events.

fix(menu): allow closing the menu via the trigger

---

src/IconButton/index.scss

If you tab through a page on Chrome or Edge, IconButtons don't show evidence that they're being focused on. This is because they explicitly their set `outline` value to `inherit`. In practice, that means that they all have `outline: none`, even on `:focus-visible`.
I'm cool with us keeping the inherit behavior for the regular state, but unless there's a strong reason not to, on `:focus-visible`, let's revert the `outline` back to the default browser stylesheet.

fix(IconButton): use default browser outline styling on focus-visible

---

src/Slider/Thumbs.tsx
src/Slider/index.scss
src/Slider/index.stories.js
src/Slider/index.tsx
src/index.scss

for https://github.com/narmi/design_system/issues/1172
This adds the `<Slider>` input component. It is a dual thumb range slider.
I referenced the example in https://react-spectrum.adobe.com/react-aria/useSlider.html#useslider-hook
below is the Figma for the desired look of the Slider
and how it behaves as implemented: 
https://github.com/narmi/design_system/assets/4285085/b8ae636b-075f-4c8c-9836-dc386b60815b

feat(Slider): Add slider component

---

src/Input/index.js
src/Input/index.scss
src/TextInput/index.js
src/TextInput/index.stories.js

Adds these three states to `TextInput`:
They are located in the storybook under `TextInput > Examples`.

feat(input): add a character counter to text inputs

---

src/TextInput/index.js
src/TextInput/index.stories.js
src/TextInput/index.test.jsx

Renders the placeholder text when a label is set for multiline `<textarea>` inputs.

fix(input): render placeholder for multiline text inputs

---

src/MenuButton/index.js

fixes #1229 
Replace `react-laag` positioning engine with `Popover` from the same set of `react-aria-components`.
I love the `react-laag` positioning engine, but it's not playing nicely with how `MenuTrigger` manages open/closed state.
This fix eliminates the problem of the popover closing before the selection handler can run.

fix(MenuButton): allow selection handler to fire before closing

---

src/TextInput/index.js
src/TextInput/index.test.jsx

resolve https://github.com/narmi/design_system/issues/1237
The moral of this is not to rely on prop-spreading - in https://github.com/narmi/design_system/commit/5e8de462cf642cbbe87e2d2489ffcf83f38824d6, we added a seemingly innocent change to sometimes display an error based on exceeding a given `maxLength` prop. But in so doing we removed the error field from `nativeElementProps`, which is spread onto the `<input>` element. So the `<input>` element doesn't receive the error prop. 
The `error` attribute is nonstandard on the native input element though, so we should maybe reconsider being dependent on it.

fix(TextInput):  prop was not being passed down to native input element

---

src/LoadingShim/index.js
src/LoadingShim/index.scss
src/Toggle/index.js
src/Toggle/index.scss
src/Toggle/index.stories.js

feat(Toggle): Adds a loading and disabled state for the Toggle component

---

.storybook/main.ts
src/Slider/index.stories.tsx
src/Slider/index.tsx

A quick PR to improve the `<Slider>` storybook story. Autodocs wasn't really working well with typescript components that define prop interfaces instead of using `prop-types`, but I seem to have fixed that by using `react-docgen`. Inspired by [this comment](https://github.com/storybookjs/storybook/issues/21007#issuecomment-1430273342)
before:
after:

chore(Slider): improve story

---

src/MultiSelect/index.js
src/MultiSelect/index.stories.js

- Set a default behavior for `fieldValue`
- Add `selectedItems` prop that may be used to make a fully controlled `MultiSelect`
- Update docs

fix(MultiSelect): add selectedItems prop for fully controlled component

---

src/Tooltip/index.stories.js

Updates the documentation for `Tooltip` so that the `Tooltip` + `TextInput` example uses the `endContent` prop on `TextInput` rather than a more homespun absolute positioned element.

docs(Tooltip): use simpler endContent example for TextInput instead of absolute positioned Tooltip

---

src/Combobox/index.js

closes NDS-179
Adds some logic to the function that determines if a category should be open or not when rendering the dropdown.
This PR adds a check to see if there's a selected item, in which case design wants all other categories collapsed (the category the selected item belongs to will be open)

fix(Combobox): collapse all unselected categories when reopening

---

src/Drawer/index.js
src/Drawer/index.scss

closes NDS-175
- Remove padding from `drawer` class
- Use helper class to fix the controls at `xxl` (their original padding)
- Use `paddingSize` prop value to apply a padding helper class to the drawer content area

feat(Drawer): make padding size configurable via prop

---

src/Slider/index.scss

The z-index being 4 here resulted in some odd behavior when interacting with the nds dialogs. There's probably a more elegant solution to make sure these play nice together, but this is the most straightforward way to solve the immediate problem. Setting the z-index to 3 here still means this component renders as expected and also fixes the issue.

fix(slider): reduce z-index on thumb

---

src/Drawer/index.scss

fix(Drawer): When padding none is set on mobile the top nav padding should be retained

---

src/util/AsElement.js
src/util/asElement.test.js

Adds support for React components to be passed in the `as` argument. This allows the use of `Link` from `react-router-dom` as the element type for a `Button`, for example.

feat(AsElement): support react component element types

---

src/RadioButtons/index.js
src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

Adds a row `kind` to the `RadioButtons` component.
Implementation Details:
Flex parent div with:
- `justify-content: space-between`
Usage:
`<RadioButtons kind="row" />`

feat(RadioButton): Add inline row kind

---

src/Checkbox/index.js

https://linear.app/narmi/issue/AO-876/beneficiaries-qa
Beneficiaries designs call for setting an error state on a group of checkboxes, but checkbox only allows for an error string to enable the error state on them.
This adds `hasError` prop to the checkbox that sets the error className and causes the red outline if hasError is true.

add hasError prop to checkbox

---

src/CollapsibleCard/index.js
src/CollapsibleCard/index.scss
src/CollapsibleCard/index.stories.js
src/IconButton/index.js
src/IconButton/index.scss

Closes NDS-193
- refactor header to use `Row` layout
- add `trigger` prop to configure which part of the card acts as the open/close trigger
- prevent hover on entire card when in "caret" trigger mode
- Remove invalid rule from 'plain' variant

feat(CollapsibleCard): add option for caret trigger

---

src/IconButton/index.js
src/IconButton/index.stories.js

Adds support to make `IconButton` use any tag, such as `<a>`.

feat(IconButton): support configuring the icon button element tag

---

src/Drawer/index.js
src/Drawer/index.scss

resolves BANKW-821
- `X`, `chevron-left` and `chevron-right` icons under `drawer--vertical--mobile` were being affected by styles meant specifically for the navigation icon buttons
- added a classname `mobile-navigation-button` to the navigation icon's parent in order to make the styles more targeted 
- this is also consistent with how the navigation icons exist in non-mobile view where the parent has a `navigation-button` classname

fix(Drawer): add classname to navigation icons in mobile drawer

---

src/TextInput/index.js

Previously, the `input` underlying the `TextInput` component was always set to `required`.
This led to unexpected browser behavior such as this pop-up for a field that wasn't actually required:
This PR preserves the existing behavior -- defaulting the input to be required -- while allowing individual `TextInput` instances to override it as needed.

feat(TextInput): allow component to control native HTML 'required' attribute

---

src/DropdownTrigger/index.js
src/DropdownTrigger/index.scss
src/Input/index.scss

close https://github.com/narmi/design_system/issues/1309
Hard to tell from this screenshot, but the error text for the `Select` component is now consistent with other input components (namely, `TextInput`)
I've also noticed that `TextInput` has more space between the input field and the error message - this is caused by the recent addition of the character counter. I think we're better off without that space, so I've removed it
<br />

fix(Select): fix text size for Select error

---

src/Checkbox/index.js
src/Checkbox/index.scss
src/Checkbox/index.stories.js

Top margin was added to normal checkboxes that are subsequent siblings to normal checkboxes in https://github.com/narmi/design_system/pull/1089/files#diff-cfd872c173d6e6389363869af77b48becfc03fed480f697ec12eee4faea06f6aR7-R10
This results in spacing that is too large for our "filter chip" dropdowns, so we have to use custom styling to fend off the extra margin.
What we want:
What we get with the default:
To preserve backwards compatibility, I've added a new "condensed" kind that is like "normal", but without the extra top margin when there are multiple checkboxes. In my heart of hearts, I think the "normal" margin should be the one that changes, but I don't want to break anything.
Here's the Storybook in action:
https://github.com/user-attachments/assets/82909764-6ac9-4c18-be2f-fe3fb515874 …

feat(Checkbox): add condensed Checkbox

---

src/Combobox/index.js

Design would like to have a Combobox that doesn't have a up/down chevron indicating whether the Combobox is open/closed.
To address that in a more extensible way, I propose letting the consumer supply a `renderEndContent` function that receives an `isOpen` prop.

feat(Combobox): allow custom end content

---

src/Combobox/index.js
src/Combobox/index.scss
src/Select/index.js
src/Select/index.scss

I noticed that if you supply an `errorText` prop to a Combobox with children, the error highlighting doesn't apply to the border of the input.
This is different from the behavior for Select, for example:
As of this PR, the red border will apply to both the input and dropdown borders for both Combobox and Select:
I somewhat blindly followed some existing patterns, e.g.
https://github.com/narmi/design_system/blob/e75a10a84b6fd9f9d4296d0450f749d206f78f53/src/Select/index.js#L277-L281
and
https://github.com/narmi/design_system/blob/a468bba33e847a01f07b79197ef2f3b82bf42ce3/src/Combobox/index.js#L256-L262
I'm open to suggestions for other ways of doing this

fix(Combobox, Select): color both input and dropdown borders on error

---

src/Tooltip/index.scss

Closes NDS-460
Reduces horizontal spacing in tooltip per design

fix(Tooltip): use even spacing around tooltip content

---

src/RadioButtons/index.js

resolve https://github.com/narmi/design_system/issues/1333
This PR changes the `RadioButtons` component to use the `Error` component instead of rolling its own error rendering. 
This makes it so that the error text font size is consistent with design standards (small font size or 12px).

fix(RadioButtons): make error text small font size

---

src/Popover/index.js
src/Popover/index.stories.js

closes NDS-572
Accessibility fix and controlled Popover improvement.
The `Popover` component was designed to behave as uncontrolled by default, and controlled when `isOpen` is passed in.
To close the popover based on user dismissal events, we provided an `onUserDismiss` callback that the parent can use to manage the `isOpen` state.
The poor assumption was that in controlled mode, we would be using a trigger somewhere outside the `Popover` children. If you want a fully controlled popover with a normal trigger defined in `children`, you would have to define your own interactive element with event handlers. This is bad because the `Popover` automatically wraps its children in a `role="button"` which is invalid.
**This PR adds the `onUserEnable` method so a parent of `Popover` may manage …

feat(Popover): add onUserEnable prop for controlled mode

---

src/Row/RowItem.js
src/Row/index.js

Often in `./staff` we would save a lot of code if we could just override the `Row` and `Row.Item` `className` opposed to having to create a wrapper div with the extra styling requirements.

feat(Row): Add className override support for Row and Row.Item

---

src/Dialog/index.scss

Closes NDS-401
Automatically add padding to the bottom of the content area equal to the height of the gradient when content is overflowing. This prevents the gradient from covering up the last line of text when you scroll to the bottom of the content area.

fix(Dialog): prevent overflow gradient text overlap

---

src/Dialog/index.scss

Closes NDS-570
Per design, makes the `Dialog` have a header style that matches our native mobile app when at small viewports.
Our `Dialog` has always taken over the full screen below the smallest viewport. Now the header changes visual display and we leave a little at the top of the screen so you can see the shim peek through

feat(Dialog): use condensed header in mobile viewports

---

src/Checkbox/index.scss

Follow-up to https://github.com/narmi/design_system/pull/1315.
One consequence of this PR is that spacing for groups of condensed checkboxes needs to be handled by the consumer. That's fine by me -- the purpose of the "condensed" style is to be un-opinionated about spacing.

fix(Checkbox): remove top-padding for subsequent sibling condensed checkboxes

---

src/MultiSelect/index.js

closes NDS-378
We observed the `MultiSelect` component stealing focus on page load in the staff app.
It looks like the prop getters being used on the `DropdownTrigger` inside the multiselect were competing over binding refs and events.
This PR resolves the issue by:
- Creating a separate, dedicated element around the `DropdownTrigger` to receive the `ref` for the `userLayer` positioning engine
- Simplify the downshift props being passed to the `DropdownTrigger` by applying only the `getToggleButtonProps` from the `useSelect` hook
-----
The `triggerProps` returned by the `useLayer` positioning engine does one thing, and only one thing: it applies a `ref` to an element so the element may be used as the positioning reference.
Wrapping the `DropdownTrigger` in a div does effectively the same …

fix(MultiSelect): prevent field autofocus

---

src/RadioButtons/index.js
src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

Closes NDS-568
Adds new RadioButtons variant, `input-card`.

feat(RadioButtons): add kind 'input-card'

---

src/DisabledShim/index.scss
src/DisabledShim/index.stories.js
src/DisabledShim/index.tsx
src/index.js
src/index.scss
src/index.ts

closes NDS-569
Adds a `DisabledShim` with the same basic interface as `LoadingShim`. This component allows disabling an arbitrary area of the screen (e.g. the contents of a card)

feat(DisabledShim): add component to disable arbitrary areas

---

src/RadioButtons/index.js
src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

closes NDS-461
Adds `checkmark` variant of `RadioButtons`. Useful for popovers with selection.
Example of where this would be used:
Screenshot from storybook preview:

feat(RadioButtons): add checkmark variant

---

src/TokenInput/index.jsx
src/TokenInput/index.stories.js

closes NDS-428
`TokenInput` originally cleared the input value on blur. This PR removes that behavior per design.

fix(TokenInput): stop clearing input on blur

---

src/MultiSelect/index.js
src/MultiSelect/index.scss

Closes NDS-621
Closes NDS-639
- Remove the placeholder label text when the component has at least one selection
- Change layout mode of tokens from _inline_ to _flex_
Tokens now wrap nicely and the selectedItems state looks better in general:

fix(MultiSelect): apply even spacing to tokens; hide label on selection

---

src/Combobox/ComboboxAction.js
src/Combobox/index.js
src/Combobox/index.scss
src/Combobox/index.stories.js
src/Row/RowItem.js
src/Row/index.js

Closes NDS-458
Adds support for passing a `Combobox.Action` to Combobox. Matches the same pattern we use in `Select.Action` components.
When a user clicks or selects an action via keyboard, the menu will close and the `onSelect` callback of the action item will be invoked.
When filtering by text, the actions will **always** be visible at the bottom of the list of suggestions.
Developers may place an Action item at any position of the list, including inside a category. When filtering, all actions will appear at the bottom of the list as usual.
See storybook preview posted below to test the new feature.

feat(Combobox): add Combobox.Action support

---

src/CollapsibleCard/index.js
src/CollapsibleCard/index.scss
src/CollapsibleCard/index.stories.js

closes NDS-586
- Updates disabled state to use `DisabledShim` (per design)
- Adds `renderTitle` render function to allow complete customization within the clickable title area
We got a bit too specific with our content slots when shipping `CollapsibleCard`, and our design team has been experimenting with slightly different content for this component in some features. 
The `renderTitle` render prop allows developers to define whatever they want as the content of the title area. Implementing this as a render prop function allows the consumer to use the `isOpen` state of the card to conditionally render things.

feat(CollapsibleCard): update disabled state; add renderTitle prop

---

src/CollapsibleCard/index.js
src/CollapsibleCard/index.scss

closes NDS-717
Allows border radius of `CollapsibleCard` to be configured via props. Sets "m" as default.

feat(CollapsibleCard): add radiusSize prop to configure border radius

---

src/Avatar/index.scss
src/Avatar/index.stories.tsx
src/Avatar/index.tsx
src/index.js
src/index.scss
src/index.ts

closes https://linear.app/narmi/issue/NDS-638/%5Bavatar%5D-new-nds-component
Initial implementation of `Avatar` component
- Supports 3 sizes xs, s, m
- Supports an optional image background
- Supports an optional link. If you click the avatar button, it will navigate you to that link.

feat(Avatar): Implement Avatar Component

---

src/ContentCard/index.js
src/ContentCard/index.scss
src/ContentCard/index.stories.js

Closes NDS-755
We use `ContentCard` in both Transfer menu cards (acting as buttons) and product selection cards in AO (acting as toggles).
The problem is that the `interactive` variant of `ContentCard` was being used in both places when that variant was originally only designed for the toggle behavior in AO.
This PR adds more granular `kind` props and deprecates `interactive` (in a non-breaking way).
- `toggle` - behaves like a toggle button (old `interactive` prop maps to this)
- `button` - behaves like an HTML button, without selected state

feat(ContentCard): add 'button' and 'toggle' kinds

---

src/ContextMenu/ContextMenuItem.tsx
src/ContextMenu/index.scss
src/ContextMenu/index.stories.tsx
src/ContextMenu/index.tsx
src/index.scss
src/index.ts

Implementation of ContextMenu.
- ContextMenu wraps other elements or components to enable a list of menu items. 
- The list of menu items can be open by right clicking on the wrapped element or press "Control + F12" when the wrapper element is focused.
- Since there is no consist way to open context menu from the OS level, instruction for opening context menu is included in aria-label.
- The implementation of this component is influence by MenuButton 
https://linear.app/narmi/issue/ADMIN-4019/[frontend]-add-right-click-menu

Create a custom context menu

---

src/index.js

ContextMenu was included in `index.ts` but I didn't realize it also need to be export it in `index.js`. This fix should make sure ContextMenu can be imported properly.
Ticket: https://linear.app/narmi/issue/ADMIN-4066/[frontend]-fix-context-menu-export-issue

fix(ContextMenu): fix missing export for ContextMenu in index.js

---

src/DisabledShim/index.scss

For [AO-2050](https://linear.app/narmi/issue/AO-2050/staff-led-status-is-misaligned-header-color-incorrect). Add full-width to `disabledShim`

fix(disabledShim): Add full width to disabledShim

---

.storybook/main.ts

Currently Storybook uses `react-docgen` for generating documentations from type definition for components written in TypeScript. Although it is faster than `react-docgen-typescript` but it is incomplete based on the [Storybook Documentation](https://storybook.js.org/docs/api/main-config/main-config-typescript#reactdocgen). It is unable to properly show union of string literals. 
**`react-docgen`**
**`react-docgen-typescript`**

refactor(Storybook): switch reactDocgen option to react-docgen-typescript

---

src/TextInput/index.js

closes NDS-839
In NDS version 4.1.0, the `error` attribute we've been adding to the underlying input elements of `TextInput` were removed because it is not a valid HTML attribute.
This however, [broke end to end tests](https://github.com/narmi/banking/actions/runs/12550357532/job/34992989179?pr=55087#step:22:170), as we relied on that attribute to make assertions.
This PR reintroduces the attribute as a data attribute, `data-error`. After this change merges we can update our e2e test assertion helper to use the data attribute in [the PR that upgrades NDS for all web products](https://github.com/narmi/banking/pull/55087)

fix(TextInput): add error data attr for e2e tests

---

src/ContextMenu/ContextMenuItem.tsx
src/json.d.ts
tsconfig.json

Previously, I suppress the TS error when importing a JSON file. Instead of doing that in all TS files, let's add a JSON module.    
Technically, we don't want to use `any` for JSON values, but I suspect we won't get too much value from making them precisely typed and the amount to work is non-trivial.    
https://linear.app/narmi/issue/NDS-837/[nds]-add-declaration-file-for-json

fix(TypeScript): add a `json.d.ts` file to remove @ts-expect-error when importing JSON file

---

src/DateInput/index.js

Closes NDS-785
The code comment in the diff explains this pretty well. When we set a certain flatpickr option via `DateInput` props (`altInput`), a new input element is created that does NOT have an aria-label.
This PR introduces an onReady event hook to ensure it does.

fix(DateInput): apply aria-label to alternate input element

---

src/Tabs/TabsTab.js
src/Tabs/index.test.js

Closes NDS-794
When Panels are included in a `Tabs` component, we link the tabs up with the panels using `role="tab"` and `aria-controls`.
When Panels are omitted, the tabs are basically just a list of links/buttons, so we do not include the `tab` role.
Without the `tab` role, the `aria-selected` attribute is invalid. This PR ensures that the `aria-selected` attribute is only present when panels are present.

fix(Tabs): only add aria attr when panels are present

---

src/Select/SelectCategory.js
src/Select/index.js
src/Select/index.scss
src/Select/index.stories.js

Closes NDS-810
Adds some additional functionality to Category subcomponents in `Select`.
- Categories may be rendered flat and open via the `isFlat` prop
- Categories may be rendered with different label types via the `kind` prop

feat(Select): allow flat categories; add label category kind

---

src/Avatar/index.stories.tsx
src/Avatar/index.tsx

closes NDS-753
When `initials` and `imgurl` are both unpopulated, the Avatar will now render a fallback user icon:

feat(Avatar): add fallback user icon

---

src/Select/index.js
src/Select/index.stories.js

Closes NDS-809
When a `Select` with `Select.Category` components present also included a `Select.Action`, the action would create its own empty category.
Example:
We now extract children a little differently, treating actions (`Select.Action`) as a different set than selectable options (`Select.Item`). 
Separating these out gives us full control over how each renders, which allows us to ensure the actions always render in a flat list at the bottom of the options list.
`Select.Action` and `Select.Children` are merged into the `items` array that gets passed to the Downshift hook. Downshift uses the `items` array by index to keep track of hover/arrow/selection states.
In the storybook preview build, see the "Flat Categories" story of `Select`, which now contains an action.

fix(Select): allow actions when using categories

---

src/RadioButtons/index.js
src/RadioButtons/index.scss

Adds "row-start" to the kind prop for Radio buttons
Removes the justify: space-between and adds a gap

feat(RadioButtons): add kind "row-start" to radio buttons

---

src/Select/index.js
src/Select/index.scss

closes NDS-849
Category headers render as `h4` html elements. There are some places in `banking` that still rely on the `nds-typography` class, which includes `font-size` and `font-weight` rules for all heading tags, causing awkwardly big category headers:
- Increase specificity of Select category label styles
- Remove vertical padding from collapsible categories

fix(Select): increase cateogry header style specificity

---

src/AutocompleteModal/index.scss

When the number of auto complete items are not enough to take up all the vertical space, it will show white background. This behavior is caused by using fixed height on `AutocompleteModal`. 
Ticket: https://linear.app/narmi/issue/NDS-850/[nds]-make-autocompletemodal-height-adjustable

fix(AutocompleteModal): make AutocompleteModal height adjust to small amount of items

---

src/Alert/index.tsx
src/index.ts

Closes NDS-875
Converts `Alert` component to typescript.
You may notice most properties in the interface are marked optional. This is because the component has default values for almost everything.

refactor(Alert): convert Alert to typescript

---

src/Button/Spinner.tsx
src/Button/index.stories.tsx
src/Button/index.tsx
src/index.ts

Closes NDS-872
Convert `Button` to typescript.
Once nice thing I noticed is that typescript hints will in fact carry the JSdoc comments with them in NDS, as we preserve comments in definition files.
Pretty neat:

refactor(Button): convert Button to typescript

---

src/Drawer/index.js

closes NDS-675
The Drawer had some nice hot keys assigned to page through panels using up/down arrows. Unfortunately, this can conflict with key bindings in child components.
- Removed arrow key bindings
- Converted control divs to `button` elements for easier keybaord nav
- Added an aria `region` around the content area that can be announced when prev/next buttons are used
- Used aria attributes to link up the buttons with the panel they control

fix(Drawer): improve controls accessibility

---

src/Radio/index.scss

relates to NDS-922
We do NOT want to select every input inside `.nds-singleRadio` to hide it visually; only the `type="radio"` input.

fix(Radio): narrow scope of input selector

---

src/Button/index.tsx

Prevents type errors on optional prop `kind` in the `Button` component.

fix(Button): make kind prop optional as it has a default val

---

src/Alert/index.tsx

Added `paddingSize` prop to the Alert component for more flexible padding control. The default 20px padding can be excessive in certain cases, like inside a modal.

feat(Alert): add paddingSize prop to control padding

---

src/Dialog/index.scss
src/Dialog/index.stories.js
src/Dialog/index.tsx

closes NDS-978
We recently made a fix for iOS Safari to make Dialog positioning mobile keyboard aware, but we introduced a regression.
The Dialog shim was positioning itself relative to the `_document_` instead of the viewport. This causes layout issues when users are scrolled down a tall document element. as we observed in NDS-977.
We always intended the DIalog to position itself relative to the viewport, so I added a root element that is positioned `fixed`.
Any `absolute` children of the root element will use the _nearest positioned parent_ instead of the document as its positioning reference.F
Yes.

fix(Dialog): position shim relative to viewport instead of document

---

src/TruncatedAccount/index.js
src/TruncatedAccount/index.scss
src/TruncatedAccount/index.stories.js

closes NDS-1053
Adds `isInline` prop to allow inline display of `TruncatedAccount`

feat(TruncatedAccount): add option for inline rendering

---

src/Radio/index.scss
src/RadioButtons/index.scss

Closes NDS-799
While we do have a `:focus` style for radio buttons, the only thing it does is darken the outline of the faux radio. When a radio set already has a selection (see below), there is no visual change to indicate the element is focused.
☝️ The user is focused on the second radio in this set, but you'd never know it by looking at it.
To indicate focus, we can use the same visual treatment we use in `Checkbox`:

fix(Radios): restore focus ring

---

src/Button/index.scss

Fix https://linear.app/narmi/issue/NDS-1076/[nds]-background-overflows-on-secondary-button

fix(Button): fix secondary background overflow

---

src/Dialog/index.tsx
src/Drawer/index.js
src/base-styles/portal.scss
src/index.scss

Previous PR (https://github.com/narmi/design_system/pull/1532) address the z-index issue among a few NDS components. 
This PR includes z-index and position changes to make sure portal outlet element is properly overlay on top of other non-NDS components in the app when they use z-index. 
The following is an example of the issue I'm trying to address. The action bar with header "Applications" has the a z-index of 2.

fix(Drawer,Dialog): apply position and z-index on portal outlet

---

src/Combobox/index.js
src/ContextMenu/index.tsx
src/Drawer/index.stories.js
src/MenuButton/index.js
src/MultiSelect/index.js
src/Popover/index.js
src/Select/index.js
src/Tooltip/index.tsx
src/util/dom.ts

In the previous version (v4.10.4) of NDS. We created a `<div id="outlet"></div>` for rendering the portal for Drawer and Dialog. It didn't occurred to me that all components that uses "useLayer" hook should use the same outlet. This PR makes sure all components that use portals share the same outlet so they stack properly.

fix(useLayer): render components using useLayer within portal div with id "outlet"

---

src/Dialog/index.scss
src/Dialog/index.tsx

Closes NDS-1100
As Wenting helpfully pointed out, there's a specific area of the screen where you click the shim and nothing happens.
As it turns out the `FocusTrap` renders a div that has an `auto` width at screen sizes larger than `s`. 
This PR fixes this issue so that the focus trap element "shrink wraps" to the dialog area so it doesn't cover up the shim and intercept shim clicks.

fix(Dialog): prevent focus trap el from blocking shim clicks

---

src/index.js

In the `index.js`, `ProgressBar` was being imported from `./Pagination`. This PR updates the import to occur from `./ProgressBar`

fix: use correct ProgressBar import

---

src/Combobox/index.js
src/Combobox/index.stories.js

Closes NDS-1134
The input should blur when an action is selected in the combobox dropdown, but that wasn't happening.  We missed this bug because `Dialog` correctly has a focus trap and steals focus from the input. When using a `Combobox.Action` to open a `Drawer`, the drawer does not steal focus and the document.activeElement is still the combobox input behind the shim.
This PR fixes this by ensuring the input is always blurred when a `Combobox.Action` is selected.
- Capture input ref in downshift's prop getter
- When selection changes to an action, blur the input in addition to closing the menu

fix(Combobox): blur input when selecting actions

---

src/TextInput/index.js

Closes NDS-1143
Per design, change `TextInput` char counter behavior to _always_ show the counter, even at 0.

fix(TextInput): show char counter at 0 chars

---

src/MultiSelect/index.js
src/MultiSelect/index.scss
src/MultiSelect/index.stories.js

resolves https://linear.app/narmi/issue/CDB-748/[web]-add-summary-mode-to-multiselect-add-clear-all-button
This adds a summary mode to the MultiSelect component.
Fixes a bug around controlled state updates.
Adds a clear all button.

feat(MultiSelect): Adds the new customizable summary mode and clear-all

---

src/MenuButton/index.js
src/MenuButton/index.stories.js
src/Popover/index.js
src/Popover/index.stories.js

Closes NDS-1229
Adds a `renderTrigger` render prop to `Popover` and `MenuButton` with the signature `(isOpen) => <>jsx</>`.
`Popover` has up to this point accepted `props.children` as the trigger. This PR deprecates that behavior in favor of the improved `renderTrigger`.
`MenuButton` deprecates it's `trigger` prop, which only accepts static JSX, unaware of the open state of the menu.

feat(Popover,MenuButton): add renderTrigger render props

---

src/Combobox/index.js
src/Combobox/index.test.js

Closes NDS-1243
We include `Combobox.Action` components passed via props in the list of `items` we pass to the downshift `useCombobox` hook to manage. The default behavior of downshift is to change the `selectedItem` in its state reducer, which was including `Action` subcomponents. Because an `Action` has no `value`, the `selectedItem` would become null and deselect the currently selected item whenever someone selects an `Action`.
The downshift hooks like `useCombobox` can take a custom state reducer. This PR leverages the state reducer we're already passing in to ensure that the new state object returned by the reducer does not change the `selectedItem`.

fix(Combobox): ensure selecting actions does not change selectedItem

---

src/Combobox/index.js
src/Combobox/index.stories.js

Closes NDS-1243
The [recent fix we merged for this issue](https://github.com/narmi/design_system/pull/1581) didn't completely work. I found that the enhancements we have added over time sort of painted us into a corner with complexity around managing downshift events.
This PR shifts most of the logic we need to accomplish the desired behaviors (unit tests pass) to the `stateReducer` we pass into the `useCombobox` config. 
This not only makes the code easier to work with, but resolves some of the chicken/egg problems that were inherent with the approach of using event hooks in addition to the state reducer to manage some of the same behaviors (e.g. blur).
- simplify and change order of things in downshift's `onInputValueChange` event hook
- move all other logic about combobox state to the …

fix(Combobox): persist selection when users select an action

---

src/MenuButton/index.js

Closes NDS-1278
Adds popup positioning control to `MenuButton` using the same props API as `Popover`.
Needed for `SplitButton` component in review.
See `MenuButton` story in the storybook preview build.

feat(MenuButton): add positioning api from Popover

---

.storybook/main.ts

Closes NDS-1225
Enables strict mode for local storybook development. Allows us to see warnings about deprecated react and react-dom features.

docs: enable storybook strict mode for local dev

---

tokens/src/color/system.json

closes NDS-1101
Updates color tokens for "system colors".
**See also:** [Figma file](https://www.figma.com/design/Yvi9XpMVbCH0B6zTIaz374/design-system-audit?node-id=4036-7&t=5wWfrwljgNAUa8ob-0)

feat(tokens): update 'system' colors for improved contrast

---

src/Button/index.scss
src/Button/index.tsx
src/Button/sizes.scss
src/Button/states.scss
src/Button/variants.scss
src/MenuButton/MenuButtonItem.js
src/MenuButton/index.js
src/Popover/index.js
src/SplitButton/SplitButtonMenu.tsx
src/SplitButton/SplitButtonPopover.tsx
src/SplitButton/index.scss
src/SplitButton/index.stories.js
src/SplitButton/index.tsx
src/index.scss

Closes NDS-981
- Move state, variant, and size styles for button into [sass placeholders](https://sass-lang.com/documentation/style-rules/placeholder-selectors/) to make them reusable
- Update styles for `nds-button` to use placeholders
- Add component
- Consume `Button` placeholder selectors to style custom trigger to match the main button
Placeholders allow us to share the same style rules we apply to `Button` sizes, variants, and states with `SplitButton`.
Any selector in Sass that starts with `%` is a "placeholder". The rule block defined under a placeholder will **not** be emitted as CSS. Placeholders allow us to share blocks of CSS via the `@extend` directive. 
What's actually happening under the hood is that Sass hoists the selector being extended to a multiple selector that …

feat(SplitButton): add SplitButton component

---

src/Combobox/index.js
src/Combobox/index.stories.js
src/Select/index.js
src/Select/index.stories.js

Closes NDS-1350
- memoize children to array processing in `Combobox` and `Select`
- ensure component rerenders the items in the dropdown when `children` change in both components
- add stories as test cases

fix(Combobox,Select): force a rerender when children change

---

src/Drawer/index.js
src/Drawer/index.scss

Closes NDS-894
Like `Dialog`, we need a focus trap so that focus moves circularly through all focusable elements in Drawer when Drawer is open (including drawer controls).
I noticed on mobile, the controls don't have a focus ring. This is because we were absolutely positioning the button _contents_ (the spans rendering the icons) rather than the button itself. Absolute positioning takes them out of document flow, causing the actual button elements that are the focusable to have no natural width or height, hiding the focus ring from view.
Fixed by moving positioning rules to the buttons themselves rather than the icons.

fix(Drawer): enable focus trap; restore focus rings on mobile controls

---

src/Button/index.scss
src/Button/sizes.scss
src/Button/variants.scss
src/SplitButton/index.scss

Closes NDS-1353
When we merged `SplitButton` in `4.18.0`, the refactoring of button styles in to Sass placeholders missed two important things with the `plain` variant of `Button`...
- I forgot to define the variant class in `Button/index.scss`
- I forgot that `kind="plain"` buttons need an override for font weight instead of inheriting from `sizes` placeholders
This PR addresses both to restore `Button kind="plain"` to it original styling.
You can check this older, pre-regression storybook deployment for the **expected** styles: https://60620d422ffdf100216415b2-vnjujhnpnl.chromatic.com/?path=/docs/components-button--docs
For the **actual** styles in this PR, see the Storybook comment in this conversation thread.
They should match.

fix(Button): style fixes for 'plain' kind

---

src/Button/index.scss

There was extra margin applied when a button was of kind menu.
|current|this pr|
|---|---|
|<img width="1193" alt="Screenshot 2025-04-24 at 1 34 32 PM" src="https://github.com/user-attachments/assets/24dad7d2-90b2-4590-97d5-a8bc8cdf5cbc" />|<img width="1193" alt="Screenshot 2025-04-24 at 1 46 14 PM" src="https://github.com/user-attachments/assets/739738ec-ecbc-468c-a676-39ffec589049" />|

fix(Button): menu buttons had gotten extra padding

---

src/Combobox/index.js

from https://linear.app/narmi/issue/BDB-896/recipient-select-menu-stays-open-after-selection
A slight behaviour change: when making a selection on Combobox, close the selector.
This matches the behaviour on the `<Select>` component. When either of these components supports `multiple` we should leave the selector open until blur, but until that happens we should default to closing the selector.
Also noticed that clicks on the down-chevron weren't expanding the selector, so added an onClick to handle

fix(Combobox): minimize selector upon selection

---

src/RadioButtons/index.tsx

The error div should have no additional margin if kind is either row or row-start.

fix(radio-buttons): add missing row-start kind

---

src/SplitButton/index.stories.js
src/SplitButton/index.tsx

I noticed in NDS 4.18.4 that I need to supply `kind="primary"` and `size="m"` for SplitButton, despite these props having defaults.
If that's intentional, feel free to close this PR.
As a drive-by, I also cleaned up two typos in these files.

fix(SplitButton): don't require props that have a default

---

src/DropdownTrigger/index.scss
src/FieldToken/index.scss

On firefox the label for the dropdown trigger blocks the block down trigger.
If you add `pointer-events: none` it allows the click to pass through. Then one must reapply the `pointer-event` for the `FieldToken`.

fix(Dropdowntrigger): On firefox the label blocks the dropdown trigger

---

package-lock.json
package.json
src/Combobox/index.js
src/Combobox/index.stories.js
src/Combobox/index.test.js

for https://github.com/narmi/design_system/issues/1605
Notably, I don't see this in prod builds - it's not reproducible https://narmi.github.io/design_system/?path=/story/components-combobox--with-categories, but it is reproducible running the same story locally. 
When clearing an input, we see an error in the console detailing that the max update depth has exceeded. 
---
On further testing, there were multiple cases where we would introduce the infinite update exception, mostly oriented around how we did not make the `stateReducer` a pure function. This PR removes the blur handling and selected item change handling out of that function and into other functions provided by downshift

fix(combobox): resolve infinite re-render issues with combobox

---

src/Button/variants.scss

Closes NDS-1477
When making fixes to the `plain` button variant, I missed that the `negative` button shares a common rule to reset margin to `0`.
This fix restores the expected spacing when a negative button is placed in a `Row` next to a primary button. This pattern is typically used in dialogs and is covered by the "cancel and confirm" story of Button.
See the storybook preview published to this PR below. Visit the "cancel and confirm" story under `Button`.

fix(Button): remove extra negative button spacing

---

src/Button/variants.scss

Relates to NDS-1400
https://linear.app/narmi/issue/NDS-1400/[design-system]-plain-button-variant-minor-regression#comment-c13abbb3
Prevents base `overflow: hidden` rule on buttons from cutting off long text in plain and negative buttons.

fix(Button): allow overflow in plain and negative buttons

---

package-lock.json
package.json
release.config.js

- [NDS-1363: \[docs,build\] add `semantic-release-npm-deprecate` to NDS](https://linear.app/narmi/issue/NDS-1363/docsbuild-add-semantic-release-npm-deprecate-to-nds)

chore(semantic-release): deprecate versions 4.18.0 - 4.18.2, which contain a Button component style regression

---

tokens/src/color/narmi.json

Adds the "AI purple" used in various new staff designs to mark AI features:
The yellowish color in the gradient here is the existing `var(--color-sand)`.

feat(colors): add amethyst, aka AI purple

---

package-lock.json
package.json
release.config.js

Disables release deprecation in `semantic-release` so we can unblock some failed actions

chore: remove deprecation plugin from release process

---

src/Button/variants.scss

closes NDS-1503
The long deprecated `menu` variant of `Button` is still being used in the OLB header, and some CSS in banking is also targeting these elements. This is a bad situation, so we will remove the `menu` kind in the next major release.
The changes here ensure menu buttons are properly aligned regardless of what element they render via `as`, or what other banking styles are targeting these elements.

fix(Button): consistently align 'menu' variant

---

.github/workflows/chromatic-main.yaml
.github/workflows/chromatic-pr.yaml
package.json

- Always build storybook with JSON stats for chromatic. 
- Update chromatic workflows to manually build storybook, using our full NDS build

chore: build storybook with stats

---

src/Row/index.scss

Closes NDS-1538
[As Elliot discovered](https://linear.app/narmi/issue/NDS-1538/regression-row-alignment-has-broken-potentially-across-multiple#comment-0a1020e2), there's a case where a Row containing items with certain height rules may have incorrect alignment due to the `height: 100%` rule on row items.
This rule was added by me, based on old habits for browsers we no longer need to support.
We should not expect or accept _any_ changes in snapshot tests.

fix(Row): rm outdated item hight fix for IE

---

.github/workflows/stale.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/39](https://github.com/narmi/design_system/security/code-scanning/39)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the minimal permissions required for the `actions/stale` action to function. Based on the action's functionality, it needs `contents: read`, `issues: write`, and `pull-requests: write` permissions. These permissions allow the action to read repository contents, manage issues, and manage pull requests, which are necessary for marking stale issues and pull requests.
The `permissions` block will be added directly under the `name` field to apply to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. …

Potential fix for code scanning alert no. 39: Workflow does not contain permissions

---

.github/workflows/release.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/38](https://github.com/narmi/design_system/security/code-scanning/38)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will define the least privileges required for the workflow to function correctly. Based on the provided steps, the workflow primarily interacts with the repository contents and requires write access for the release process. Therefore, we will set `contents: write` as the minimal required permission.
---

Potential fix for code scanning alert no. 38: Workflow does not contain permissions

---

.github/workflows/github-pages.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/35](https://github.com/narmi/design_system/security/code-scanning/35)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the minimal permissions required for the workflow to function. Based on the workflow's steps, it primarily interacts with repository contents (e.g., checking out code and deploying to GitHub Pages). Therefore, we will set `contents: write` to allow deployment and restrict all other permissions.
---

Potential fix for code scanning alert no. 35: Workflow does not contain permissions

---

.github/workflows/chromatic-main.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/28](https://github.com/narmi/design_system/security/code-scanning/28)
To fix the issue, add a `permissions` block to the workflow to explicitly define the least privileges required for the job. Since the workflow does not perform any write operations on the repository, the `contents: read` permission is sufficient. This ensures that the `GITHUB_TOKEN` has only read access to the repository contents, reducing the risk of unintended modifications.
The `permissions` block can be added at the root level of the workflow to apply to all jobs or within the specific job (`chromatic_update_baseline`) to limit its scope.
---

Potential fix for code scanning alert no. 28: Workflow does not contain permissions

---

.github/workflows/chromatic-pr.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/30](https://github.com/narmi/design_system/security/code-scanning/30)
To fix the issue, we need to add a `permissions` block to the workflow. This block should specify the minimum permissions required for the workflow to function correctly. Based on the workflow's operations, the following permissions are appropriate:
- `contents: read` to allow the workflow to read repository contents.
- `pull-requests: write` to allow the workflow to post comments on pull requests.
The `permissions` block can be added at the root level of the workflow to apply to all jobs, or it can be added to individual jobs. In this case, adding it at the root level is more efficient since both jobs (`run_chromatic` and …

Potential fix for code scanning alert no. 30: Workflow does not contain permissions

---

.github/workflows/jest.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/34](https://github.com/narmi/design_system/security/code-scanning/34)
To fix the issue, add a `permissions` block at the root level of the workflow file. This block will explicitly define the permissions required for the workflow, limiting the `GITHUB_TOKEN` to read-only access to repository contents. This ensures that the workflow operates securely and adheres to the principle of least privilege.
The `permissions` block should be added immediately after the `name` field in the workflow file. The permissions required for this workflow are minimal, so `contents: read` is sufficient.
---

Potential fix for code scanning alert no. 34: Workflow does not contain permissions

---

.github/workflows/lint.yaml

Potential fix for [https://github.com/narmi/design_system/security/code-scanning/36](https://github.com/narmi/design_system/security/code-scanning/36)
To fix the issue, we will add a `permissions` block at the root of the workflow file. Since the workflow only needs to read the repository contents to perform linting, we will set `contents: read`. This ensures that the workflow has the minimum required permissions and adheres to security best practices.
---

Potential fix for code scanning alert no. 36: Workflow does not contain permissions

---

.github/workflows/chromatic-main.yaml
.github/workflows/chromatic-pr.yaml
.github/workflows/github-pages.yaml

Closes NDS-1609
- For read/write actions, pin to a specific commit hash per [Unpinned tag for a non-immutable Action in workflow](https://github.com/narmi/design_system/security/code-scanning/22)

chore: pin actions to hashes code-scanning/24

---

src/Combobox/index.js
src/Combobox/index.test.js

Closes NDS-1628
Updates `onSelectedItem` downshift event handler to call the `props.onChange` function of Combobox with an empty string (instead of erroring) when a user clears the value of the input.

Combobox: fix `onSelectedItem` handler for user-cleared inputs

---

src/MultiSelect/MultiSelectItem.js
src/MultiSelect/index.js
src/MultiSelect/index.stories.js

Closes NDS-1352
**Features**
- `getTypeaheadString` prop added to MultiSelect, using the [same signature and implementation as Select](https://github.com/narmi/design_system/blob/67c82bfdae0f05b1f96c1287b7232b9d75b0abea/src/Select/index.stories.js#L232)
**Fixes**
- Refactored our state management to bring things closer to downshift defaults
- Enabled selection by Enter key to render the token as expected

Add `getTypeaheadString` prop to `MultiSelect`

---

src/ContextMenu/ContextMenuItem.tsx
src/ContextMenu/index.test.tsx
src/ContextMenu/index.tsx
src/Dialog/index.test.tsx
src/Dialog/index.tsx

- Adds tests for the `ContextMenu` component and updates the null handling for `onSelect`
- Adds tests for the `Dialog` component and addresses a deprecation warning for `findDOMNode`

chore: Add `ContextMenu` & `Dialog` tests

---

.github/workflows/chromatic-pr.yaml

The chromatic PR check will never run on pull requests that do not contain changes in the `src` or `tokens` directories. However, the check is a required workflow and will prevent merging. For example, see https://github.com/narmi/design_system/pull/1701
This updates the workflow to early exit if changes in `src` or `tokens` do not exist

ci: Adjust chromatic workflow to early exit on NA changes

---

src/CollapsibleCard/index.js
src/CollapsibleCard/index.scss

Closes NDS-1662
- refactors the duplicated props and className in this component to be a bit cleaner
- adds a CSS class to the card, triggering `height: auto` when `renderTitle` is used.

fix(CollapsibleCard): use auto height for closed card when using renderTitle

---

src/Input/index.scss

- [NDS-1745: (web): calendar picker on payment activity](https://linear.app/narmi/issue/NDS-1745/web-calendar-picker-on-payment-activity)
When the `portalDisabled` prop is set on `<DateInput />`, it renders the component next to the parent input, as opposed to at the bottom of the DOM. The parent input is wrapped by a `.nds-input` div, which adheres to global CSS rules that interfere with the styling of the `flatpickr` date component. The solution was to exclude any `input` components rendered by the `flatpickr` date component within the global CSS rule using the `:not()` selector.
Before|After
--|--

fix(DateInput): Ignore globally set `input` CSS rules for `portalDisabled` `<DateInput/>` components

---

src/DateInput/index.js
src/TableDateInput/index.stories.tsx
src/TableDateInput/index.tsx

Closes NDS-1756
Adds a new table input type, `TableDateInput`.
- Add render prop for the input element used in `DateInput`
- Use the new `renderInput` prop of `DateInput` to compose in a `TableInput`

Nds 1757/table date input

---

src/Table/index.tsx
src/Table/util/breakpoint.ts

Closes NDS-1789
In [the bug we observed](https://linear.app/narmi/issue/NDS-1789/potential-table-bug-ach-payment-activity), the Table component was falling back to `repeat(5, 1fr)` for its derived `grid-template-columns` inline style. 
Whenever `Table` sees a mismatch between the number of visible columns and the `colLayout` config for that breakpoint, it falls back to something sensible by making every column `1fr`. **However**, there are only supposed to be 4 visible columns at `m` and `Table` thinks there are 5.
As it turns out, there was a mismatch between our breakpoint hook `useBreakpoints` and `Table`. Specifically, `isBreakpointSatisfied`, which Table uses to determine which columns are visible.
The `Table` component only takes "s", "m", and "l" by design, but the hook can return …

fix(Table): make layout config inclusive of XL bp

---

src/Button/index.scss
src/Button/sizes.scss

Closes NDS-1746
Allow only the `m` button size to scale its height on mobile viewports.

fix(Button): prevent small buttons from scaling on mobile

---

src/TableInput/index.scss
src/TableInput/index.stories.tsx
src/TableInput/index.tsx

Closes NDS-1791
- Move border and spacing styles to root element instead of the input itself
- Add character counter and `maxLength` prop
- Place input and character counter in a flex, preventing overlap with user-entered text

feat(TableInput): add maxLength prop with char counter

---

src/Pagination/index.js
src/Pagination/index.scss
src/Pagination/index.test.js
src/Pagination/usePagination.test.ts
src/Pagination/usePagination.ts

Closes NDS-1768
Refactor core pagination logic into a react hook; uses a more standard UX behavior matching this example: <https://atlassian.design/components/pagination/examples>
- Remove `_getAttributes` helper function
- Add `usePagination` to calculate attributes needed for rendering
- Add tests for `usePagination`
There aren't many libraries that expose pagination logic in a convenient hook, and most of them manage the `onPageChange` responsibility. It was frankly easier to roll my own using material and atlassian as implementation references.
These are the parts that usePagination is managing...
**Red:** the "sliding window" aka `visiblePages`
**Blue:** the ellipsis that appear when the first or last page is outside the visible window respectively
**Lime:** first and last pages …

feat(Pagination): use sliding window behavior

---

src/base-styles/scss-utils.scss
src/hooks/useDropdownLayer/index.ts

Closes NDS-1854
The `{...layerProps}`/"layer" element that `useDropdownLayer` is supposed to position must have a z-index.
I was relying on existing CSS to do this, but the element that _looks_ like a dropdown may not always be the same element that positions the dropdown. This change ensures the z-index responsibility is on the hook.

fix(Combobox,Select): write inline zindex

---

src/Table/index.scss

- [NDS-1839: Add radius to corners of table row](https://linear.app/narmi/issue/NDS-1839/add-radius-to-corners-of-table-row)
https://github.com/user-attachments/assets/95ab1608-2808-4c7e-bd96-4aa59e67906e

fix(Table.Row): Add border radius to `only-of-type` rows

---

src/Radio/index.scss
src/Radio/index.stories.js
src/Radio/index.tsx

Closes NDS-1873
Adds a new variant to `Radio` to display each option as a rating button. Consumers are responsible for layout of the buttons, which may be composed with `Row`.
https://60620d422ffdf100216415b2-nzvcjkizgf.chromatic.com/iframe.html?globals=&args=&id=components-radio--as-rating&viewMode=story

Support `kind="rating"` in `Radio`
