README.md

shows if latest build on `master` is passing

docs: add build badge

---

src/Dropdown/index.js
src/Dropdown/index.stories.js

closes https://github.com/narmi/design_system/issues/572
Pass error prop to TextInput in Dropdown

fix(Dropdown): Allow user to pass error to Dropdown

---

src/Tooltip/index.js
src/Tooltip/index.scss

resolves https://github.com/narmi/design_system/issues/607

[tooltip] L: Add max-width of 500

---

src/RadioButtons/index.scss
src/RadioButtons/index.stories.js

closes https://github.com/narmi/design_system/issues/420

fix(RadioButtons) : Small style changes from design feedback

---

src/Button/index.scss

fixes #631 
Use secondary theme color for plain button

fix(Button): use secondary theme color for plain button

---

src/Tag/index.scss

Small change to get tags more in line with the design ask.

fix(Tag): font size should be xs

---

package-lock.json
package.json

testing eslint because it does weird things in CI

downgrade eslint

---

.eslintrc.js
scripts/component-adoption.mjs
src/Card/index.stories.js
src/ContentCard/index.js
src/Dropdown/index.js
src/DropdownTrigger/index.test.js
src/Select/SelectAction.js
src/Select/SelectItem.js
src/Tabs/index.test.js
src/Tag/index.stories.js
src/TextInput/index.js
src/TextInput/index.stories.js
src/TextInput/index.test.jsx
src/util/asElement.test.js

relates to:
- #482 
Enables `no-unused-vars` lint rule and fixes errors.

refactor: enable `no-unused-vars` lint rule; fix errors

---

.github/workflows/lint.yaml

fixes #674 
Introduces eslint github workflow to run on all PRs

build: run eslint workflow on PRs

---

src/Checkbox/index.js

related to narmi/banking#18175
looks like the event wasn't being passed along into `onChange`

fix(Checkbox): forward event to onChange

---

src/formatters/formatNumber.js

Adding further browser support.
For https://github.com/narmi/banking/issues/18403

fix(numberformat): Add native JS failover

---

src/formatters/formatNumber.js

For https://github.com/narmi/banking/issues/19538

fix(formatting): Expect decimal representation in backfall percent formatter

---

src/TruncatedAccount/index.js
src/TruncatedAccount/index.scss
src/TruncatedAccount/index.stories.js
src/index.js
src/index.scss

fixes https://github.com/narmi/banking/issues/20170
Adds `TruncatedAccount` component.

feat(TruncatedAccount): add `TruncatedAccount` component

---

src/Tag/index.scss

now possible with https://github.com/narmi/design_system/pull/780

chore(tag): convert to using xxs font size from hardcoded value

---

src/index.stories.mdx

fixes #695 
Add a feedback link to storybook welcome page

docs(storybook): add feedback link

---

src/Dialog/index.stories.js
src/Popover/index.js

Close popover if user clicks on content, optional prop
https://user-images.githubusercontent.com/23458204/189941226-3f790826-a111-4132-9fdb-02c38c8a9753.mov

fix(Popover): close popover if user clicks on content, optional prop

---

src/RadioButtons/index.scss

close https://github.com/narmi/design_system/issues/807

fix(RadioButtons): card-style radio buttons should have font weight bold and color theme primary

---

src/Button/index.js
src/Button/index.stories.js
src/Button/index.test.js

fixes https://github.com/narmi/design_system/issues/851

feat(Button): add `xs` as valid size option

---

README.md

Forces a release that includes this commit: https://github.com/narmi/design_system/pull/852#pullrequestreview-1186812380

feat(Button): add `xs` size option

---

src/Drawer/index.js
src/Drawer/index.scss
src/Drawer/index.stories.js
src/Drawer/useLockBodyScroll.js
src/Drawer/useMountTransition.js
src/index.js
src/index.scss

Drawer component that opens up via an animation:
https://user-images.githubusercontent.com/40327446/208700326-e3ca2e55-20b2-4632-89f4-b263c5db21ab.mov
Component's API:

feat(Drawer): add Drawer component

---

src/Tabs/index.scss

fixes https://github.com/narmi/design_system/issues/829

fix(Tabs): set selected tab's font weight to semibold

---

src/Tag/index.js
src/Tag/index.scss

Result:
https://user-images.githubusercontent.com/40327446/210803890-77fd51af-8a0d-4d5e-8378-aaf5f82d51ea.mov

feat(Tag): add success, warn and error variants

---

src/RadioButtons/index.scss

for https://github.com/narmi/banking/issues/26643
For the comment: spacing btwn the button and text also seems too big (should be 28px padding)

fix(radiobuttons): Decrease padding between option and text

---

src/Drawer/index.js
src/Drawer/index.scss

This makes the navigation buttons bigger, more spaced, and with better hover states, in addition to making the drawer animation less abrupt.
Before:
https://user-images.githubusercontent.com/40327446/215914718-c0f767b8-14cb-40ad-a5e5-c4718c753e57.mov
After:
https://user-images.githubusercontent.com/40327446/215914806-159eced8-00c9-40b6-a4c5-d0bbe2eaece3.mov

fix(Drawer): update navigation panel design

---

src/Tag/index.js
src/Tag/index.scss

feat(Tag): add new `grey` kind

---

src/Tag/index.js
src/Tag/index.scss

fix(Tag): change `grey` Tag to `subdued-secondary`

---

src/Input/index.scss

resolves https://github.com/narmi/banking/issues/27833
was:
Is now:

fix(Input): error color wins against focus color

---

src/Select/index.js
src/Select/index.stories.js

resolves https://github.com/narmi/design_system/issues/891

fix(select): correctly render with less than two options

---

src/DropdownTrigger/index.scss
src/Select/index.scss

resolves https://github.com/narmi/design_system/issues/901

fix(Select): minor style changes

---

src/Button/Spinner.js
src/FormSection/index.js
src/FormSection/index.scss
src/FormSection/index.stories.js
src/index.js
src/index.scss

closes #905 
Adds `FormSection` component.
```jsx
<FormSection title="Personal Details">{/* form components */}</FormSection>
```

feat(FormSection): add FormSection component

---

src/Input/index.js
src/Input/index.scss
src/TextInput/index.js
src/TextInput/index.stories.js

Sample:
https://github.com/narmi/design_system/assets/40327446/0ea68904-2f69-48fc-b0e8-b3dc4b6b742c

feat(TextInput): add support for clear input icon

---

src/RadioButtons/index.js

Adds aria-label to the Radio buttons.

fix(Radio): add aria-label

---

src/icons/style.css

from https://github.com/narmi/banking/issues/25927
sets the text-rendering style on icons

style(icons): set text-rendering: geometricPrecision;

---

src/RadioButtons/index.js

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role
Seems like a better fit than `img`.
For https://github.com/narmi/banking/issues/32271

fix(radio): set check icon to presentation role

---

src/Tooltip/index.js

https://github.com/narmi/banking/issues/32271

fix(tooltip): add aria-label to tooltip trigger

---

.github/workflows/build.yaml
.github/workflows/github-pages.yaml
.github/workflows/jest.yaml
.github/workflows/lint.yaml
.github/workflows/publish_storybook.yaml
.github/workflows/release.yaml
package-lock.json
package.json

recommend node 18 and use node 18 while doing any CI operations

chore(node): recommend node 18 instead of 16

---

src/Button/index.js

feat(button): Create optional button input for ariaLabel

---

src/Tabs/TabsList.js

fix(tabslist): Tabslist scroll removal throwing error

---

package-lock.json
package.json
src/Checkbox/index.js
src/Checkbox/index.scss
src/Checkbox/index.stories.js
src/Checkbox/index.test.js

https://github.com/narmi/banking/issues/33922

feat(checkbox): Allow markdown

---

src/Tabs/TabsList.js

resolves https://github.com/narmi/design_system/issues/979

fix(tabs): non-responsive tabs should not be flex

---

src/ContentCard/index.js
src/ContentCard/index.scss

resolves https://github.com/narmi/design_system/issues/987

feat(ContentCard): add bordered kind

---

src/ContentCard/index.js

closes https://github.com/narmi/design_system/issues/825

feat(ContentCard): add radiusSize prop

---

src/Tabs/index.scss
src/Tabs/index.stories.js

resolves https://github.com/narmi/design_system/issues/996

fix(tabs): responsive tab titles should not wrap

---

src/Select/index.scss

fix(Select): Max-height 50vh

---

src/icons/style.css

part of #35947
I need to make the icon white, so need to remove the color specification here.

fix(icon): remove color from filter-2

---

src/Error/index.stories.js
src/index.js

resolves https://github.com/narmi/design_system/issues/755

feat(Error): expose component publicly

---

src/Input/index.scss
src/TextInput/index.js
src/TextInput/index.stories.js

resolves https://github.com/narmi/design_system/issues/1027

fix(TextInput): support the 'time' and 'datetime-local' types

---

src/Combobox/index.js

We still want to pass the value into the onChange and onInputChange functions

patch(Combobox): Use combobox value for new selection

---

src/Button/index.js
src/Button/index.scss

https://github.com/narmi/design_system/assets/23458204/f336021c-e53a-46b0-9c51-a618dc1338ee
For https://github.com/narmi/design_system/issues/912
The Button component will maintain it's color when loading. The label will be hidden but the size of the button should remain the same. The spinner should be centered.

fix(Button): Update isLoading styles

---

src/Combobox/index.js

relates to #1044 
Per design, the combobox input will clear when the user revisits the input and starts to type new characters. The selection will not change until the user actively moves the selection to a new item.
https://github.com/narmi/design_system/assets/231252/8326dfa8-d5a6-4a5d-ace8-af799b1c8082

feat(Combobox): add clearing behavior when revisiting a completed input

---

src/Checkbox/index.stories.js

Having zero ESLint warnings is a good feeling.

chore(storybook): fix minor lint warning

---

src/ProgressBar/index.js
src/ProgressBar/index.scss
src/ProgressBar/index.stories.js
src/index.js
src/index.scss

closes #1104 
Adds `ProgressBar`.
We can add a `kind` prop later if we need to, but for now, we match the style of the file upload progress bar.

feat(ProgressBar): add ProgressBar component

---

CHANGELOG.md

bumps version for changes introduced in #1121

feat(Alert): add testid prop

---

src/Input/index.scss

closes #1093 
- Fix incorrect bgColor var
- Disable user selection on disabled inputs

fix(TextInput): restore disabled background color

---

src/Sidebar/index.js

closes https://github.com/narmi/design_system/issues/1171
adds Sidebar.Item

fix(Sidebar): map SidebarItem to Sidebar.Item

---

src/index.js

In https://github.com/narmi/design_system/pull/1214, I forgot to add the `<Slider>` component to the root export 🤦

fix(Slider): export Slider

---

src/Button/index.js

fixes linear NDS-276
Ensure we don't try to map over `undefined` in `TimelineEvent`.

fix(TimelineEvent): fix iconSelection map

---

src/TruncatedAccount/index.js
src/TruncatedAccount/index.stories.js

resolves https://github.com/narmi/design_system/issues/1241

fix(TruncatedAccount): prevent 'lastFour' from wrapping

---

package-lock.json
package.json
src/Button/index.scss
src/Checkbox/index.scss
src/CollapsibleCard/index.scss
src/Combobox/index.scss
src/DateInput/index.scss
src/DropdownTrigger/index.scss
src/Error/index.scss
src/FieldToken/index.scss
src/FormSection/index.js
src/IconButton/index.scss
src/Input/index.scss
src/LoadingSkeleton/index.scss
src/Pagination/index.scss
src/ProgressBar/index.js
src/ProgressBar/index.scss
src/RadioButtons/index.scss
src/Select/index.scss
src/base-styles/scss-utils.scss
src/index.scss
tokens/config.js
tokens/util/transforms.js

closes NDS-103
Browsers offer an accessibility feature that allows users to change their base font size:
What this setting actually does is update the user agent stylesheet with a different `font-size` value for `body`.
Until recently, we had so much legacy UI in `banking`, it wasn't worth making this work until we cleaned up a bit. Now that we're in a better state with legacy styles, it's time to respect user font size preferences, starting with the NDS base styles.
- Update our `style-dictionary` config so that any font or radius related tokens are generated as `rem` units. This is where the CSS vars come from.
- Add `rem` scss helper to NDS for any value that needs to scale with font size (e.g. nudging icons with transform)
- Replaced hard coded `px` values in NDS with variables …

Feature: fontsize respects user preferences

---

src/index.ts

Forces release for: https://github.com/narmi/design_system/pull/1319

refactor(typescript): enable type hints in consumers

---

src/IconButton/index.js
src/IconButton/index.scss
src/IconButton/index.stories.js

closes https://github.com/narmi/design_system/issues/1176
https://github.com/user-attachments/assets/350417ba-e70f-45b0-b371-c4a45c519c08

feat(IconButton): add `themed` variant

---

src/TimelineEvent/index.js
src/TimelineEvent/index.stories.js

ref FED-287 
Adds support for tooltip for the icon. Will allow for use in the fednow manager components.

feat(timelineEvent): Add support for a tooltip to TimelineEvent

---

src/Dialog/index.scss

resolves https://github.com/narmi/design_system/issues/1392

fix(Dialog): remove left padding from header in desktop mode

---

README.md

Forcing a release; the original PR did not contain a commit type of feature

feat(ContextMenu): add ContextMenu component

---

src/Dialog/index.stories.js
src/Popover/index.stories.js
src/TextInput/index.js
src/TextInput/index.test.jsx

We recently upgraded eslint react plugin, and this PR fixes some new violations the linter caught.
This unblocks other PRs in review.

chore: fix new lint violations

---

tokens/config.js

Request from Alex N
Closes NDS-846
Adds a build config for `style-dictionary` that builds our design tokens in a nested json format.
This makes it easier for our design team to reference the latest values in Figma variables.
When we build and publish, `dist/` will now contain a `dist/tokens/json/tokens.json` like this:
```json
{
"border": {
"color": {
"primary": "#1A4338",
"light": "#D9D9D9",
"default": "#D9D9D9"
},
"radius": {
"s": "4px",
"m": "8px",
"l": "20px",
"default": "4px"
},
"size": {
"s": "1px",
"m": "2px",
"default": "1px"
}
},
"color": {
"alpha": {
"5": "0.05",
"10": "0.1",
"20": "0.2"
},
"background": {
"blueGrey": "#F4F6FA",
"cloudGrey": "#E9E9E9",
"neutralGrey": "#F9F9F9",
"smokeGrey": "#F3F3F3",
"snowGrey": "#FBFBFB",
"white": "#FFFFFF",
"scrimLight": "rgba(255, 255, 255, …
```

feat(tokens): add json dist for design tokens

---

src/Dialog/index.js

fix(Dialog): Add padding if content is overflowing

---

src/Tooltip/index.tsx
src/index.ts

Closes NDS-879
Converts `Tooltip` to typescript.

refactor(Tooltip): convert Tooltip to typescript

---

src/Tabs/Arrow.tsx
src/Tabs/TabsList.tsx
src/Tabs/TabsPanel.tsx
src/Tabs/TabsTab.tsx
src/Tabs/context.ts
src/Tabs/index.tsx
src/index.ts

https://linear.app/narmi/issue/NDS-887/[nds-typescript]-convert-tabs-to-typescript

refactor(Tabs): convert Tabs to TypeScript

---

src/Checkbox/index.tsx
src/index.ts

https://linear.app/narmi/issue/NDS-878/[nds-typescript]-convert-checkbox-to-typescript

refactor(Checkbox): convert Checkbox to TypeScript

---

src/Radio/index.scss
src/Radio/index.stories.js
src/Radio/index.tsx
src/index.js
src/index.scss
src/index.ts

Closes NDS-922
Adds the `Radio` component, for rendering single radio inputs with full control over labels and markup between radios.

feat(Radio): add single Radio component

---

src/Button/index.tsx

Removes console.log from `Button` component

fix(Button): remove console log

---

CHANGELOG.md
package-lock.json
package.json
src/Alert/index.tsx
src/Button/index.tsx
src/ContentCard/index.tsx
src/Dialog/index.tsx
src/RadioButtons/index.tsx

Unblocks NDS upgrades due to type errors:
e.g. https://github.com/narmi/banking/actions/runs/13059724173/job/36439440220?pr=56395

fix: prevent TS errors in consumers

---

tokens/src/color/color.stories.js

Fix some incorrect titles from earlier Storybook migration v8 work.
Close: https://linear.app/narmi/issue/NDS-930/[storybook-docs]-some-incorrect-titles

fix incorrect colors

---

src/Combobox/ComboboxHeading.js
src/Combobox/index.js
src/Combobox/index.scss
src/Combobox/index.stories.js

closes NDS-780
Adds `hint` variant for `Combobox.Heading` Items.

feat(Combobox): add hint variant for heading items

---

src/Dialog/index.tsx
src/Drawer/index.js
src/Drawer/index.scss
src/Drawer/index.stories.js

Adds a `z-index` and `position: relative;` to create a new stacking context. This gives the page 100 z-indexes to use for stacking without interfering with the drawer.

fix(drawer): add a z-index and position

---

src/MultiSelect/index.js

Memoizes the children to stop a dependency loop.

fix(MultiSelect): Fix infinite loop due to non-memoized dependency for controlled components

---

src/MenuButton/index.js

- [NDS-1366: SplitButton with MenuButton does not toggle](https://linear.app/narmi/issue/NDS-1366/splitbutton-with-menubutton-does-not-toggle)

fix(MenuButton): allow menu toggling

---

src/Row/index.tsx

close https://github.com/narmi/design_system/issues/1636
quick PR to allow us to use this value to style NDS Rows.

feat(Row): support `center` for `justifyContent` prop
